// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: common.proto

package commonservice

import (
	"context"

	"common/common"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetCaptchaRequest  = common.GetCaptchaRequest
	GetCaptchaResponse = common.GetCaptchaResponse
	Result             = common.Result

	CommonService interface {
		GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error)
	}

	defaultCommonService struct {
		cli zrpc.Client
	}
)

func NewCommonService(cli zrpc.Client) CommonService {
	return &defaultCommonService{
		cli: cli,
	}
}

func (m *defaultCommonService) GetCaptcha(ctx context.Context, in *GetCaptchaRequest, opts ...grpc.CallOption) (*GetCaptchaResponse, error) {
	client := common.NewCommonServiceClient(m.cli.Conn())
	return client.GetCaptcha(ctx, in, opts...)
}
