// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: configcenter.proto

package configcategoryservice

import (
	"context"

	"configcenter/configcenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfigCategoryData          = configcenter.ConfigCategoryData
	ConfigItemData              = configcenter.ConfigItemData
	ConfigOptionItem            = configcenter.ConfigOptionItem
	ConfigValueItem             = configcenter.ConfigValueItem
	CreateCategoryRequest       = configcenter.CreateCategoryRequest
	CreateCategoryResponse      = configcenter.CreateCategoryResponse
	CreateConfigRequest         = configcenter.CreateConfigRequest
	CreateConfigResponse        = configcenter.CreateConfigResponse
	DeleteCategoryRequest       = configcenter.DeleteCategoryRequest
	DeleteCategoryResponse      = configcenter.DeleteCategoryResponse
	DeleteConfigRequest         = configcenter.DeleteConfigRequest
	DeleteConfigResponse        = configcenter.DeleteConfigResponse
	GetCategoryAllRequest       = configcenter.GetCategoryAllRequest
	GetCategoryAllResponse      = configcenter.GetCategoryAllResponse
	GetCategoryDetailRequest    = configcenter.GetCategoryDetailRequest
	GetCategoryDetailResponse   = configcenter.GetCategoryDetailResponse
	GetCategoryListRequest      = configcenter.GetCategoryListRequest
	GetCategoryListResponse     = configcenter.GetCategoryListResponse
	GetConfigByCategoryRequest  = configcenter.GetConfigByCategoryRequest
	GetConfigByCategoryResponse = configcenter.GetConfigByCategoryResponse
	GetConfigDetailRequest      = configcenter.GetConfigDetailRequest
	GetConfigDetailResponse     = configcenter.GetConfigDetailResponse
	GetConfigListRequest        = configcenter.GetConfigListRequest
	GetConfigListResponse       = configcenter.GetConfigListResponse
	GetConfigValueRequest       = configcenter.GetConfigValueRequest
	GetConfigValueResponse      = configcenter.GetConfigValueResponse
	SaveConfigValueRequest      = configcenter.SaveConfigValueRequest
	SaveConfigValueResponse     = configcenter.SaveConfigValueResponse
	UpdateCategoryRequest       = configcenter.UpdateCategoryRequest
	UpdateCategoryResponse      = configcenter.UpdateCategoryResponse
	UpdateConfigRequest         = configcenter.UpdateConfigRequest
	UpdateConfigResponse        = configcenter.UpdateConfigResponse
	UpdateConfigStatusRequest   = configcenter.UpdateConfigStatusRequest
	UpdateConfigStatusResponse  = configcenter.UpdateConfigStatusResponse

	ConfigCategoryService interface {
		GetList(ctx context.Context, in *GetCategoryListRequest, opts ...grpc.CallOption) (*GetCategoryListResponse, error)
		GetAll(ctx context.Context, in *GetCategoryAllRequest, opts ...grpc.CallOption) (*GetCategoryAllResponse, error)
		GetDetail(ctx context.Context, in *GetCategoryDetailRequest, opts ...grpc.CallOption) (*GetCategoryDetailResponse, error)
		Create(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
		Update(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
		Delete(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	}

	defaultConfigCategoryService struct {
		cli zrpc.Client
	}
)

func NewConfigCategoryService(cli zrpc.Client) ConfigCategoryService {
	return &defaultConfigCategoryService{
		cli: cli,
	}
}

func (m *defaultConfigCategoryService) GetList(ctx context.Context, in *GetCategoryListRequest, opts ...grpc.CallOption) (*GetCategoryListResponse, error) {
	client := configcenter.NewConfigCategoryServiceClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultConfigCategoryService) GetAll(ctx context.Context, in *GetCategoryAllRequest, opts ...grpc.CallOption) (*GetCategoryAllResponse, error) {
	client := configcenter.NewConfigCategoryServiceClient(m.cli.Conn())
	return client.GetAll(ctx, in, opts...)
}

func (m *defaultConfigCategoryService) GetDetail(ctx context.Context, in *GetCategoryDetailRequest, opts ...grpc.CallOption) (*GetCategoryDetailResponse, error) {
	client := configcenter.NewConfigCategoryServiceClient(m.cli.Conn())
	return client.GetDetail(ctx, in, opts...)
}

func (m *defaultConfigCategoryService) Create(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	client := configcenter.NewConfigCategoryServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultConfigCategoryService) Update(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	client := configcenter.NewConfigCategoryServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

func (m *defaultConfigCategoryService) Delete(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	client := configcenter.NewConfigCategoryServiceClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
