// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: develop.proto

package server

import (
	"context"

	"develop/develop"
	"develop/internal/logic/developservice"
	"develop/internal/svc"
)

type DevelopServiceServer struct {
	svcCtx *svc.ServiceContext
	develop.UnimplementedDevelopServiceServer
}

func NewDevelopServiceServer(svcCtx *svc.ServiceContext) *DevelopServiceServer {
	return &DevelopServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DevelopServiceServer) GetList(ctx context.Context, in *develop.GetListRequest) (*develop.GetDevelopListResponse, error) {
	l := developservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *DevelopServiceServer) GetContent(ctx context.Context, in *develop.GetDevelopContentRequest) (*develop.GetDevelopContentResponse, error) {
	l := developservicelogic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}

func (s *DevelopServiceServer) UpStatus(ctx context.Context, in *develop.UpStatusRequest) (*develop.UpStatusResponse, error) {
	l := developservicelogic.NewUpStatusLogic(ctx, s.svcCtx)
	return l.UpStatus(in)
}

func (s *DevelopServiceServer) Del(ctx context.Context, in *develop.DelRequest) (*develop.DelResponse, error) {
	l := developservicelogic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *DevelopServiceServer) DelTplCode(ctx context.Context, in *develop.DelTplCodeRequest) (*develop.DelTplCodeResponse, error) {
	l := developservicelogic.NewDelTplCodeLogic(ctx, s.svcCtx)
	return l.DelTplCode(in)
}

func (s *DevelopServiceServer) UninstallCode(ctx context.Context, in *develop.UninstallCodeRequest) (*develop.UninstallCodeResponse, error) {
	l := developservicelogic.NewUninstallCodeLogic(ctx, s.svcCtx)
	return l.UninstallCode(in)
}

func (s *DevelopServiceServer) GetDbField(ctx context.Context, in *develop.GetDbfieldRequest) (*develop.GetDbfieldResponse, error) {
	l := developservicelogic.NewGetDbFieldLogic(ctx, s.svcCtx)
	return l.GetDbField(in)
}

func (s *DevelopServiceServer) GetMenuParent(ctx context.Context, in *develop.GetDevelopMenuParentRequest) (*develop.GetDevelopMenuParentResponse, error) {
	l := developservicelogic.NewGetMenuParentLogic(ctx, s.svcCtx)
	return l.GetMenuParent(in)
}

func (s *DevelopServiceServer) GetTableList(ctx context.Context, in *develop.GetTableListRequest) (*develop.GetTableListResponse, error) {
	l := developservicelogic.NewGetTableListLogic(ctx, s.svcCtx)
	return l.GetTableList(in)
}

func (s *DevelopServiceServer) CheckedHaseTable(ctx context.Context, in *develop.CheckedHaseTableRequest) (*develop.CheckedHaseTableResponse, error) {
	l := developservicelogic.NewCheckedHaseTableLogic(ctx, s.svcCtx)
	return l.CheckedHaseTable(in)
}

func (s *DevelopServiceServer) UpCodeTable(ctx context.Context, in *develop.UpCodeTableRequest) (*develop.UpCodeTableResponse, error) {
	l := developservicelogic.NewUpCodeTableLogic(ctx, s.svcCtx)
	return l.UpCodeTable(in)
}

func (s *DevelopServiceServer) GetGoVueDir(ctx context.Context, in *develop.GetGoVueDirRequest) (*develop.GetGoVueDirResponse, error) {
	l := developservicelogic.NewGetGoVueDirLogic(ctx, s.svcCtx)
	return l.GetGoVueDir(in)
}

func (s *DevelopServiceServer) MarkTplCode(ctx context.Context, in *develop.MarkTplCodeRequest) (*develop.MarkTplCodeResponse, error) {
	l := developservicelogic.NewMarkTplCodeLogic(ctx, s.svcCtx)
	return l.MarkTplCode(in)
}
