// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	gaBusinessAccountFieldNames          = builder.RawFieldNames(&GaBusinessAccount{})
	gaBusinessAccountRows                = strings.Join(gaBusinessAccountFieldNames, ",")
	gaBusinessAccountRowsExpectAutoSet   = strings.Join(stringx.Remove(gaBusinessAccountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	gaBusinessAccountRowsWithPlaceHolder = strings.Join(stringx.Remove(gaBusinessAccountFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	gaBusinessAccountModel interface {
		Insert(ctx context.Context, data *GaBusinessAccount) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*GaBusinessAccount, error)
		Update(ctx context.Context, data *GaBusinessAccount) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultGaBusinessAccountModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GaBusinessAccount struct {
		Id            uint64       `db:"id"`
		AccountId     int64        `db:"account_id"`      // 账号id/记录那个账号添加
		BusinessId    int64        `db:"business_id"`     // 业务主账号id
		MainAccount   int64        `db:"main_account"`    // 是否为主账号:0=否,1=是
		DeptId        int64        `db:"dept_id"`         // 部门id
		Username      string       `db:"username"`        // 用户账号
		Password      string       `db:"password"`        // 密码
		Salt          string       `db:"salt"`            // 密码盐
		Name          string       `db:"name"`            // 姓名
		Nickname      string       `db:"nickname"`        // 昵称
		Avatar        string       `db:"avatar"`          // 头像
		Tel           string       `db:"tel"`             // 备用电话用户自己填写
		Mobile        string       `db:"mobile"`          // 手机号码
		Email         string       `db:"email"`           // 邮箱
		LastLoginIp   string       `db:"last_login_ip"`   // 最后登录IP
		LastLoginTime int64        `db:"last_login_time"` // 最后登录时间
		Status        int64        `db:"status"`          // 状态0=正常，1=禁用
		Validtime     int64        `db:"validtime"`       // 账号有效时间0=无限
		Address       string       `db:"address"`         // 地址
		Remark        string       `db:"remark"`          // 描述
		Company       string       `db:"company"`         // 公司名称
		Province      string       `db:"province"`        // 省份
		City          string       `db:"city"`            // 城市
		Area          string       `db:"area"`            // 地区
		FileSize      uint64       `db:"fileSize"`        // 附件存储空间
		LoginAttempts int64        `db:"login_attempts"`  // 登录尝试次数
		LockTime      time.Time    `db:"lock_time"`       // 账号锁定时间
		CreateTime    sql.NullTime `db:"create_time"`     // 创建时间
		UpdateTime    sql.NullTime `db:"update_time"`     // 修改时间
		DeleteTime    sql.NullTime `db:"delete_time"`     // 删除时间
		PwdResetTime  sql.NullTime `db:"pwd_reset_time"`  // 修改密码时间
	}
)

func newGaBusinessAccountModel(conn sqlx.SqlConn) *defaultGaBusinessAccountModel {
	return &defaultGaBusinessAccountModel{
		conn:  conn,
		table: "`ga_business_account`",
	}
}

func (m *defaultGaBusinessAccountModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGaBusinessAccountModel) FindOne(ctx context.Context, id uint64) (*GaBusinessAccount, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", gaBusinessAccountRows, m.table)
	var resp GaBusinessAccount
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGaBusinessAccountModel) Insert(ctx context.Context, data *GaBusinessAccount) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, gaBusinessAccountRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.BusinessId, data.MainAccount, data.DeptId, data.Username, data.Password, data.Salt, data.Name, data.Nickname, data.Avatar, data.Tel, data.Mobile, data.Email, data.LastLoginIp, data.LastLoginTime, data.Status, data.Validtime, data.Address, data.Remark, data.Company, data.Province, data.City, data.Area, data.FileSize, data.LoginAttempts, data.LockTime, data.DeleteTime, data.PwdResetTime)
	return ret, err
}

func (m *defaultGaBusinessAccountModel) Update(ctx context.Context, data *GaBusinessAccount) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, gaBusinessAccountRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.AccountId, data.BusinessId, data.MainAccount, data.DeptId, data.Username, data.Password, data.Salt, data.Name, data.Nickname, data.Avatar, data.Tel, data.Mobile, data.Email, data.LastLoginIp, data.LastLoginTime, data.Status, data.Validtime, data.Address, data.Remark, data.Company, data.Province, data.City, data.Area, data.FileSize, data.LoginAttempts, data.LockTime, data.DeleteTime, data.PwdResetTime, data.Id)
	return err
}

func (m *defaultGaBusinessAccountModel) tableName() string {
	return m.table
}
