// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package dashboardservice

import (
	"context"

	"common/common"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetCaptchaRequest  = common.GetCaptchaRequest
	GetCaptchaResponse = common.GetCaptchaResponse
	GetMenuRequest     = common.GetMenuRequest
	GetMenuResponse    = common.GetMenuResponse
	GetQuickRequest    = common.GetQuickRequest
	GetQuickResponse   = common.GetQuickResponse
	GetQuickRow        = common.GetQuickRow
	Result             = common.Result

	DashboardService interface {
		GetDashboard(ctx context.Context, in *GetQuickRequest, opts ...grpc.CallOption) (*GetQuickResponse, error)
	}

	defaultDashboardService struct {
		cli zrpc.Client
	}
)

func NewDashboardService(cli zrpc.Client) DashboardService {
	return &defaultDashboardService{
		cli: cli,
	}
}

func (m *defaultDashboardService) GetDashboard(ctx context.Context, in *GetQuickRequest, opts ...grpc.CallOption) (*GetQuickResponse, error) {
	client := common.NewDashboardServiceClient(m.cli.Conn())
	return client.GetDashboard(ctx, in, opts...)
}
