// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: apilog.proto

package logservice

import (
	"context"

	"apilog/apilog"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	OperationLogRequest  = apilog.OperationLogRequest
	OperationLogResponse = apilog.OperationLogResponse

	LogService interface {
		AddOperationLog(ctx context.Context, in *OperationLogRequest, opts ...grpc.CallOption) (*OperationLogResponse, error)
	}

	defaultLogService struct {
		cli zrpc.Client
	}
)

func NewLogService(cli zrpc.Client) LogService {
	return &defaultLogService{
		cli: cli,
	}
}

func (m *defaultLogService) AddOperationLog(ctx context.Context, in *OperationLogRequest, opts ...grpc.CallOption) (*OperationLogResponse, error) {
	client := apilog.NewLogServiceClient(m.cli.Conn())
	return client.AddOperationLog(ctx, in, opts...)
}
