// 声明 proto 使用的语法版本

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.11
// source: develop.proto

// proto 包名

package develop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevelopService_GetList_FullMethodName          = "/develop.DevelopService/GetList"
	DevelopService_GetContent_FullMethodName       = "/develop.DevelopService/GetContent"
	DevelopService_UpStatus_FullMethodName         = "/develop.DevelopService/UpStatus"
	DevelopService_Del_FullMethodName              = "/develop.DevelopService/Del"
	DevelopService_DelTplCode_FullMethodName       = "/develop.DevelopService/DelTplCode"
	DevelopService_UninstallCode_FullMethodName    = "/develop.DevelopService/UninstallCode"
	DevelopService_GetDbField_FullMethodName       = "/develop.DevelopService/GetDbField"
	DevelopService_GetMenuParent_FullMethodName    = "/develop.DevelopService/GetMenuParent"
	DevelopService_GetTableList_FullMethodName     = "/develop.DevelopService/GetTableList"
	DevelopService_CheckedHaseTable_FullMethodName = "/develop.DevelopService/CheckedHaseTable"
	DevelopService_UpCodeTable_FullMethodName      = "/develop.DevelopService/UpCodeTable"
	DevelopService_GetGoVueDir_FullMethodName      = "/develop.DevelopService/GetGoVueDir"
	DevelopService_MarkTplCode_FullMethodName      = "/develop.DevelopService/MarkTplCode"
)

// DevelopServiceClient is the client API for DevelopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type DevelopServiceClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetDevelopListResponse, error)
	GetContent(ctx context.Context, in *GetDevelopContentRequest, opts ...grpc.CallOption) (*GetDevelopContentResponse, error)
	UpStatus(ctx context.Context, in *UpStatusRequest, opts ...grpc.CallOption) (*UpStatusResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	DelTplCode(ctx context.Context, in *DelTplCodeRequest, opts ...grpc.CallOption) (*DelTplCodeResponse, error)
	UninstallCode(ctx context.Context, in *UninstallCodeRequest, opts ...grpc.CallOption) (*UninstallCodeResponse, error)
	GetDbField(ctx context.Context, in *GetDbfieldRequest, opts ...grpc.CallOption) (*GetDbfieldResponse, error)
	GetMenuParent(ctx context.Context, in *GetDevelopMenuParentRequest, opts ...grpc.CallOption) (*GetDevelopMenuParentResponse, error)
	GetTableList(ctx context.Context, in *GetTableListRequest, opts ...grpc.CallOption) (*GetTableListResponse, error)
	CheckedHaseTable(ctx context.Context, in *CheckedHaseTableRequest, opts ...grpc.CallOption) (*CheckedHaseTableResponse, error)
	UpCodeTable(ctx context.Context, in *UpCodeTableRequest, opts ...grpc.CallOption) (*UpCodeTableResponse, error)
	GetGoVueDir(ctx context.Context, in *GetGoVueDirRequest, opts ...grpc.CallOption) (*GetGoVueDirResponse, error)
	MarkTplCode(ctx context.Context, in *MarkTplCodeRequest, opts ...grpc.CallOption) (*MarkTplCodeResponse, error)
}

type developServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevelopServiceClient(cc grpc.ClientConnInterface) DevelopServiceClient {
	return &developServiceClient{cc}
}

func (c *developServiceClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetDevelopListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevelopListResponse)
	err := c.cc.Invoke(ctx, DevelopService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) GetContent(ctx context.Context, in *GetDevelopContentRequest, opts ...grpc.CallOption) (*GetDevelopContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevelopContentResponse)
	err := c.cc.Invoke(ctx, DevelopService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) UpStatus(ctx context.Context, in *UpStatusRequest, opts ...grpc.CallOption) (*UpStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpStatusResponse)
	err := c.cc.Invoke(ctx, DevelopService_UpStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, DevelopService_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) DelTplCode(ctx context.Context, in *DelTplCodeRequest, opts ...grpc.CallOption) (*DelTplCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelTplCodeResponse)
	err := c.cc.Invoke(ctx, DevelopService_DelTplCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) UninstallCode(ctx context.Context, in *UninstallCodeRequest, opts ...grpc.CallOption) (*UninstallCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallCodeResponse)
	err := c.cc.Invoke(ctx, DevelopService_UninstallCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) GetDbField(ctx context.Context, in *GetDbfieldRequest, opts ...grpc.CallOption) (*GetDbfieldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDbfieldResponse)
	err := c.cc.Invoke(ctx, DevelopService_GetDbField_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) GetMenuParent(ctx context.Context, in *GetDevelopMenuParentRequest, opts ...grpc.CallOption) (*GetDevelopMenuParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevelopMenuParentResponse)
	err := c.cc.Invoke(ctx, DevelopService_GetMenuParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) GetTableList(ctx context.Context, in *GetTableListRequest, opts ...grpc.CallOption) (*GetTableListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableListResponse)
	err := c.cc.Invoke(ctx, DevelopService_GetTableList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) CheckedHaseTable(ctx context.Context, in *CheckedHaseTableRequest, opts ...grpc.CallOption) (*CheckedHaseTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckedHaseTableResponse)
	err := c.cc.Invoke(ctx, DevelopService_CheckedHaseTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) UpCodeTable(ctx context.Context, in *UpCodeTableRequest, opts ...grpc.CallOption) (*UpCodeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpCodeTableResponse)
	err := c.cc.Invoke(ctx, DevelopService_UpCodeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) GetGoVueDir(ctx context.Context, in *GetGoVueDirRequest, opts ...grpc.CallOption) (*GetGoVueDirResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoVueDirResponse)
	err := c.cc.Invoke(ctx, DevelopService_GetGoVueDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *developServiceClient) MarkTplCode(ctx context.Context, in *MarkTplCodeRequest, opts ...grpc.CallOption) (*MarkTplCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTplCodeResponse)
	err := c.cc.Invoke(ctx, DevelopService_MarkTplCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevelopServiceServer is the server API for DevelopService service.
// All implementations must embed UnimplementedDevelopServiceServer
// for forward compatibility.
//
// 定义服务
type DevelopServiceServer interface {
	GetList(context.Context, *GetListRequest) (*GetDevelopListResponse, error)
	GetContent(context.Context, *GetDevelopContentRequest) (*GetDevelopContentResponse, error)
	UpStatus(context.Context, *UpStatusRequest) (*UpStatusResponse, error)
	Del(context.Context, *DelRequest) (*DelResponse, error)
	DelTplCode(context.Context, *DelTplCodeRequest) (*DelTplCodeResponse, error)
	UninstallCode(context.Context, *UninstallCodeRequest) (*UninstallCodeResponse, error)
	GetDbField(context.Context, *GetDbfieldRequest) (*GetDbfieldResponse, error)
	GetMenuParent(context.Context, *GetDevelopMenuParentRequest) (*GetDevelopMenuParentResponse, error)
	GetTableList(context.Context, *GetTableListRequest) (*GetTableListResponse, error)
	CheckedHaseTable(context.Context, *CheckedHaseTableRequest) (*CheckedHaseTableResponse, error)
	UpCodeTable(context.Context, *UpCodeTableRequest) (*UpCodeTableResponse, error)
	GetGoVueDir(context.Context, *GetGoVueDirRequest) (*GetGoVueDirResponse, error)
	MarkTplCode(context.Context, *MarkTplCodeRequest) (*MarkTplCodeResponse, error)
	mustEmbedUnimplementedDevelopServiceServer()
}

// UnimplementedDevelopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevelopServiceServer struct{}

func (UnimplementedDevelopServiceServer) GetList(context.Context, *GetListRequest) (*GetDevelopListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedDevelopServiceServer) GetContent(context.Context, *GetDevelopContentRequest) (*GetDevelopContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedDevelopServiceServer) UpStatus(context.Context, *UpStatusRequest) (*UpStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpStatus not implemented")
}
func (UnimplementedDevelopServiceServer) Del(context.Context, *DelRequest) (*DelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedDevelopServiceServer) DelTplCode(context.Context, *DelTplCodeRequest) (*DelTplCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelTplCode not implemented")
}
func (UnimplementedDevelopServiceServer) UninstallCode(context.Context, *UninstallCodeRequest) (*UninstallCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallCode not implemented")
}
func (UnimplementedDevelopServiceServer) GetDbField(context.Context, *GetDbfieldRequest) (*GetDbfieldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDbField not implemented")
}
func (UnimplementedDevelopServiceServer) GetMenuParent(context.Context, *GetDevelopMenuParentRequest) (*GetDevelopMenuParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenuParent not implemented")
}
func (UnimplementedDevelopServiceServer) GetTableList(context.Context, *GetTableListRequest) (*GetTableListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTableList not implemented")
}
func (UnimplementedDevelopServiceServer) CheckedHaseTable(context.Context, *CheckedHaseTableRequest) (*CheckedHaseTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckedHaseTable not implemented")
}
func (UnimplementedDevelopServiceServer) UpCodeTable(context.Context, *UpCodeTableRequest) (*UpCodeTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpCodeTable not implemented")
}
func (UnimplementedDevelopServiceServer) GetGoVueDir(context.Context, *GetGoVueDirRequest) (*GetGoVueDirResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGoVueDir not implemented")
}
func (UnimplementedDevelopServiceServer) MarkTplCode(context.Context, *MarkTplCodeRequest) (*MarkTplCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkTplCode not implemented")
}
func (UnimplementedDevelopServiceServer) mustEmbedUnimplementedDevelopServiceServer() {}
func (UnimplementedDevelopServiceServer) testEmbeddedByValue()                        {}

// UnsafeDevelopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevelopServiceServer will
// result in compilation errors.
type UnsafeDevelopServiceServer interface {
	mustEmbedUnimplementedDevelopServiceServer()
}

func RegisterDevelopServiceServer(s grpc.ServiceRegistrar, srv DevelopServiceServer) {
	// If the following call panics, it indicates UnimplementedDevelopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevelopService_ServiceDesc, srv)
}

func _DevelopService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevelopContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).GetContent(ctx, req.(*GetDevelopContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_UpStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).UpStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_UpStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).UpStatus(ctx, req.(*UpStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_DelTplCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelTplCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).DelTplCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_DelTplCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).DelTplCode(ctx, req.(*DelTplCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_UninstallCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).UninstallCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_UninstallCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).UninstallCode(ctx, req.(*UninstallCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_GetDbField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDbfieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).GetDbField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_GetDbField_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).GetDbField(ctx, req.(*GetDbfieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_GetMenuParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevelopMenuParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).GetMenuParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_GetMenuParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).GetMenuParent(ctx, req.(*GetDevelopMenuParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_GetTableList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).GetTableList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_GetTableList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).GetTableList(ctx, req.(*GetTableListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_CheckedHaseTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckedHaseTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).CheckedHaseTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_CheckedHaseTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).CheckedHaseTable(ctx, req.(*CheckedHaseTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_UpCodeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpCodeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).UpCodeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_UpCodeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).UpCodeTable(ctx, req.(*UpCodeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_GetGoVueDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoVueDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).GetGoVueDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_GetGoVueDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).GetGoVueDir(ctx, req.(*GetGoVueDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DevelopService_MarkTplCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTplCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevelopServiceServer).MarkTplCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevelopService_MarkTplCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevelopServiceServer).MarkTplCode(ctx, req.(*MarkTplCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DevelopService_ServiceDesc is the grpc.ServiceDesc for DevelopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevelopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "develop.DevelopService",
	HandlerType: (*DevelopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _DevelopService_GetList_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _DevelopService_GetContent_Handler,
		},
		{
			MethodName: "UpStatus",
			Handler:    _DevelopService_UpStatus_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _DevelopService_Del_Handler,
		},
		{
			MethodName: "DelTplCode",
			Handler:    _DevelopService_DelTplCode_Handler,
		},
		{
			MethodName: "UninstallCode",
			Handler:    _DevelopService_UninstallCode_Handler,
		},
		{
			MethodName: "GetDbField",
			Handler:    _DevelopService_GetDbField_Handler,
		},
		{
			MethodName: "GetMenuParent",
			Handler:    _DevelopService_GetMenuParent_Handler,
		},
		{
			MethodName: "GetTableList",
			Handler:    _DevelopService_GetTableList_Handler,
		},
		{
			MethodName: "CheckedHaseTable",
			Handler:    _DevelopService_CheckedHaseTable_Handler,
		},
		{
			MethodName: "UpCodeTable",
			Handler:    _DevelopService_UpCodeTable_Handler,
		},
		{
			MethodName: "GetGoVueDir",
			Handler:    _DevelopService_GetGoVueDir_Handler,
		},
		{
			MethodName: "MarkTplCode",
			Handler:    _DevelopService_MarkTplCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "develop.proto",
}
