// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"system/internal/logic/accountservice"
	"system/internal/svc"
	"system/system"
)

type AccountServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedAccountServiceServer
}

func NewAccountServiceServer(svcCtx *svc.ServiceContext) *AccountServiceServer {
	return &AccountServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServiceServer) GetList(ctx context.Context, in *system.GetRoleListRequest) (*system.GetRoleListResponse, error) {
	l := accountservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *AccountServiceServer) Save(ctx context.Context, in *system.SaveAccountRequest) (*system.SaveAccountResponse, error) {
	l := accountservicelogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

func (s *AccountServiceServer) UpState(ctx context.Context, in *system.UpStatusAccountRequest) (*system.UpStatusAccountResponse, error) {
	l := accountservicelogic.NewUpStateLogic(ctx, s.svcCtx)
	return l.UpState(in)
}

func (s *AccountServiceServer) Del(ctx context.Context, in *system.DelAccountRequest) (*system.DelAccountResponse, error) {
	l := accountservicelogic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *AccountServiceServer) GetRole(ctx context.Context, in *system.GetAccountRoleRequest) (*system.GetAccountRoleResponse, error) {
	l := accountservicelogic.NewGetRoleLogic(ctx, s.svcCtx)
	return l.GetRole(in)
}

func (s *AccountServiceServer) Isaccountexist(ctx context.Context, in *system.IsAccountExistRequest) (*system.IsAccountExistResponse, error) {
	l := accountservicelogic.NewIsaccountexistLogic(ctx, s.svcCtx)
	return l.Isaccountexist(in)
}
