// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetCaptchaReq struct {
	CaptchaType string `json:"type" validate:"required"`
}

type GetLogData struct {
	Id         uint64            `json:"id"`
	Uid        uint64            `json:"uid"`
	AccountId  uint64            `json:"account_id"`
	BusinessId uint64            `json:"business_id"`
	Type       string            `json:"type"`
	Status     uint64            `json:"status"`
	Des        string            `json:"des"`
	Ip         string            `json:"ip"`
	Address    string            `json:"address"`
	UserAgent  string            `json:"user_agent"`
	ErrorMsg   string            `json:"error_msg"`
	CreateTime string            `json:"create_time"`
	User       map[string]string `json:"user"`
}

type GetMenuReq struct {
	RouteId uint64 `json:"route_id"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
	Codeid   string `json:"codeid" validate:"required"`
	Captcha  string `json:"captcha" validate:"required"`
}

type SaveQuickReq struct {
	Icon    string `json:"icon" validate:"required"`
	Id      uint64 `json:"id"`
	Name    string `json:"name" validate:"required"`
	PathUrl string `json:"path_url" validate:"required"`
	ReqType uint64 `json:"type"`
	Weigh   uint64 `json:"weigh"`
}

type GetLoginReq struct {
	Page        uint64 `form:"page,optional"`
	PageSize    uint64 `form:"pageSize,optional"`
	User        string `form:"user,optional"`
	Ip          string `form:"ip,optional"`
	Create_time string `form:"create_time,optional"`
	Status      uint64 `form:"status,optional"`
}

type GetLoginResp struct {
	Items    []GetLogData `json:"items"`
	Total    uint64       `json:"total"`
	Page     uint64       `json:"page"`
	PageSize uint64       `json:"pageSize"`
}
