// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type GetCaptchaReq struct {
	Captcha_type string `json:"captcha_type"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Codeid   string `json:"codeid"`
	Captcha  string `json:"captcha"`
}
