// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: apilog.proto

package server

import (
	"context"

	"apilog/apilog"
	"apilog/internal/logic/logservice"
	"apilog/internal/svc"
)

type LogServiceServer struct {
	svcCtx *svc.ServiceContext
	apilog.UnimplementedLogServiceServer
}

func NewLogServiceServer(svcCtx *svc.ServiceContext) *LogServiceServer {
	return &LogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LogServiceServer) AddOperationLog(ctx context.Context, in *apilog.OperationLogRequest) (*apilog.OperationLogResponse, error) {
	l := logservicelogic.NewAddOperationLogLogic(ctx, s.svcCtx)
	return l.AddOperationLog(in)
}
