// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package accountservice

import (
	"context"

	"system/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelAccountRequest          = system.DelAccountRequest
	DelAccountResponse         = system.DelAccountResponse
	DelDeptRequest             = system.DelDeptRequest
	DelDeptResponse            = system.DelDeptResponse
	DelLastLoginRequest        = system.DelLastLoginRequest
	DelLastLoginResponse       = system.DelLastLoginResponse
	DelLastOperationRequest    = system.DelLastOperationRequest
	DelLastOperationResponse   = system.DelLastOperationResponse
	DelRoleRequest             = system.DelRoleRequest
	DelRoleResponse            = system.DelRoleResponse
	DelRuleRequest             = system.DelRuleRequest
	DelRuleResponse            = system.DelRuleResponse
	DeptData                   = system.DeptData
	DeptParentData             = system.DeptParentData
	GetAccountListRequest      = system.GetAccountListRequest
	GetAccountListResponse     = system.GetAccountListResponse
	GetAccountRoleRequest      = system.GetAccountRoleRequest
	GetAccountRoleResponse     = system.GetAccountRoleResponse
	GetDeptListRequest         = system.GetDeptListRequest
	GetDeptListResponse        = system.GetDeptListResponse
	GetDeptParentRequest       = system.GetDeptParentRequest
	GetDeptParentResponse      = system.GetDeptParentResponse
	GetLogData                 = system.GetLogData
	GetLogListRequest          = system.GetLogListRequest
	GetLogListResponse         = system.GetLogListResponse
	GetMenuListRequest         = system.GetMenuListRequest
	GetMenuListResponse        = system.GetMenuListResponse
	GetOperationDetailRequest  = system.GetOperationDetailRequest
	GetOperationDetailResponse = system.GetOperationDetailResponse
	GetOperationRequest        = system.GetOperationRequest
	GetOperationResponse       = system.GetOperationResponse
	GetRoleListRequest         = system.GetRoleListRequest
	GetRoleListResponse        = system.GetRoleListResponse
	GetRoleParentRequest       = system.GetRoleParentRequest
	GetRoleParentResponse      = system.GetRoleParentResponse
	GetRoutesRequest           = system.GetRoutesRequest
	GetRoutesResponse          = system.GetRoutesResponse
	GetRuleContentRequest      = system.GetRuleContentRequest
	GetRuleContentResponse     = system.GetRuleContentResponse
	GetRuleListRequest         = system.GetRuleListRequest
	GetRuleListResponse        = system.GetRuleListResponse
	GetRuleParentRequest       = system.GetRuleParentRequest
	GetRuleParentResponse      = system.GetRuleParentResponse
	IsAccountExistRequest      = system.IsAccountExistRequest
	IsAccountExistResponse     = system.IsAccountExistResponse
	OperationLogData           = system.OperationLogData
	RoleData                   = system.RoleData
	RuleListData               = system.RuleListData
	SaveAccountRequest         = system.SaveAccountRequest
	SaveAccountResponse        = system.SaveAccountResponse
	SaveDeptRequest            = system.SaveDeptRequest
	SaveDeptResponse           = system.SaveDeptResponse
	SaveRoleRequest            = system.SaveRoleRequest
	SaveRoleResponse           = system.SaveRoleResponse
	SaveRuleRequest            = system.SaveRuleRequest
	SaveRuleResponse           = system.SaveRuleResponse
	UpStatusAccountRequest     = system.UpStatusAccountRequest
	UpStatusAccountResponse    = system.UpStatusAccountResponse
	UpStatusDeptRequest        = system.UpStatusDeptRequest
	UpStatusDeptResponse       = system.UpStatusDeptResponse
	UpStatusRoleRequest        = system.UpStatusRoleRequest
	UpStatusRoleResponse       = system.UpStatusRoleResponse
	UpStatusRuleRequest        = system.UpStatusRuleRequest
	UpStatusRuleResponse       = system.UpStatusRuleResponse

	AccountService interface {
		GetList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error)
		Save(ctx context.Context, in *SaveAccountRequest, opts ...grpc.CallOption) (*SaveAccountResponse, error)
		UpState(ctx context.Context, in *UpStatusAccountRequest, opts ...grpc.CallOption) (*UpStatusAccountResponse, error)
		Del(ctx context.Context, in *DelAccountRequest, opts ...grpc.CallOption) (*DelAccountResponse, error)
		GetRole(ctx context.Context, in *GetAccountRoleRequest, opts ...grpc.CallOption) (*GetAccountRoleResponse, error)
		Isaccountexist(ctx context.Context, in *IsAccountExistRequest, opts ...grpc.CallOption) (*IsAccountExistResponse, error)
	}

	defaultAccountService struct {
		cli zrpc.Client
	}
)

func NewAccountService(cli zrpc.Client) AccountService {
	return &defaultAccountService{
		cli: cli,
	}
}

func (m *defaultAccountService) GetList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error) {
	client := system.NewAccountServiceClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultAccountService) Save(ctx context.Context, in *SaveAccountRequest, opts ...grpc.CallOption) (*SaveAccountResponse, error) {
	client := system.NewAccountServiceClient(m.cli.Conn())
	return client.Save(ctx, in, opts...)
}

func (m *defaultAccountService) UpState(ctx context.Context, in *UpStatusAccountRequest, opts ...grpc.CallOption) (*UpStatusAccountResponse, error) {
	client := system.NewAccountServiceClient(m.cli.Conn())
	return client.UpState(ctx, in, opts...)
}

func (m *defaultAccountService) Del(ctx context.Context, in *DelAccountRequest, opts ...grpc.CallOption) (*DelAccountResponse, error) {
	client := system.NewAccountServiceClient(m.cli.Conn())
	return client.Del(ctx, in, opts...)
}

func (m *defaultAccountService) GetRole(ctx context.Context, in *GetAccountRoleRequest, opts ...grpc.CallOption) (*GetAccountRoleResponse, error) {
	client := system.NewAccountServiceClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultAccountService) Isaccountexist(ctx context.Context, in *IsAccountExistRequest, opts ...grpc.CallOption) (*IsAccountExistResponse, error) {
	client := system.NewAccountServiceClient(m.cli.Conn())
	return client.Isaccountexist(ctx, in, opts...)
}
