// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: configcenter.proto

package server

import (
	"context"

	"configcenter/configcenter"
	"configcenter/internal/logic/configitemservice"
	"configcenter/internal/svc"
)

type ConfigItemServiceServer struct {
	svcCtx *svc.ServiceContext
	configcenter.UnimplementedConfigItemServiceServer
}

func NewConfigItemServiceServer(svcCtx *svc.ServiceContext) *ConfigItemServiceServer {
	return &ConfigItemServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ConfigItemServiceServer) GetList(ctx context.Context, in *configcenter.GetConfigListRequest) (*configcenter.GetConfigListResponse, error) {
	l := configitemservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *ConfigItemServiceServer) GetByCategory(ctx context.Context, in *configcenter.GetConfigByCategoryRequest) (*configcenter.GetConfigByCategoryResponse, error) {
	l := configitemservicelogic.NewGetByCategoryLogic(ctx, s.svcCtx)
	return l.GetByCategory(in)
}

func (s *ConfigItemServiceServer) GetDetail(ctx context.Context, in *configcenter.GetConfigDetailRequest) (*configcenter.GetConfigDetailResponse, error) {
	l := configitemservicelogic.NewGetDetailLogic(ctx, s.svcCtx)
	return l.GetDetail(in)
}

func (s *ConfigItemServiceServer) Create(ctx context.Context, in *configcenter.CreateConfigRequest) (*configcenter.CreateConfigResponse, error) {
	l := configitemservicelogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *ConfigItemServiceServer) Update(ctx context.Context, in *configcenter.UpdateConfigRequest) (*configcenter.UpdateConfigResponse, error) {
	l := configitemservicelogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *ConfigItemServiceServer) Delete(ctx context.Context, in *configcenter.DeleteConfigRequest) (*configcenter.DeleteConfigResponse, error) {
	l := configitemservicelogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *ConfigItemServiceServer) UpdateStatus(ctx context.Context, in *configcenter.UpdateConfigStatusRequest) (*configcenter.UpdateConfigStatusResponse, error) {
	l := configitemservicelogic.NewUpdateStatusLogic(ctx, s.svcCtx)
	return l.UpdateStatus(in)
}

func (s *ConfigItemServiceServer) SaveValue(ctx context.Context, in *configcenter.SaveConfigValueRequest) (*configcenter.SaveConfigValueResponse, error) {
	l := configitemservicelogic.NewSaveValueLogic(ctx, s.svcCtx)
	return l.SaveValue(in)
}

func (s *ConfigItemServiceServer) GetValue(ctx context.Context, in *configcenter.GetConfigValueRequest) (*configcenter.GetConfigValueResponse, error) {
	l := configitemservicelogic.NewGetValueLogic(ctx, s.svcCtx)
	return l.GetValue(in)
}
