// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package deptservice

import (
	"context"

	"system/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelAccountRequest          = system.DelAccountRequest
	DelAccountResponse         = system.DelAccountResponse
	DelDeptRequest             = system.DelDeptRequest
	DelDeptResponse            = system.DelDeptResponse
	DelLastLoginRequest        = system.DelLastLoginRequest
	DelLastLoginResponse       = system.DelLastLoginResponse
	DelLastOperationRequest    = system.DelLastOperationRequest
	DelLastOperationResponse   = system.DelLastOperationResponse
	DelRoleRequest             = system.DelRoleRequest
	DelRoleResponse            = system.DelRoleResponse
	DelRuleRequest             = system.DelRuleRequest
	DelRuleResponse            = system.DelRuleResponse
	DeptData                   = system.DeptData
	DeptParentData             = system.DeptParentData
	GetAccountListRequest      = system.GetAccountListRequest
	GetAccountListResponse     = system.GetAccountListResponse
	GetAccountRoleRequest      = system.GetAccountRoleRequest
	GetAccountRoleResponse     = system.GetAccountRoleResponse
	GetDeptListRequest         = system.GetDeptListRequest
	GetDeptListResponse        = system.GetDeptListResponse
	GetDeptParentRequest       = system.GetDeptParentRequest
	GetDeptParentResponse      = system.GetDeptParentResponse
	GetLogData                 = system.GetLogData
	GetLogListRequest          = system.GetLogListRequest
	GetLogListResponse         = system.GetLogListResponse
	GetMenuListRequest         = system.GetMenuListRequest
	GetMenuListResponse        = system.GetMenuListResponse
	GetOperationDetailRequest  = system.GetOperationDetailRequest
	GetOperationDetailResponse = system.GetOperationDetailResponse
	GetOperationRequest        = system.GetOperationRequest
	GetOperationResponse       = system.GetOperationResponse
	GetRoleListRequest         = system.GetRoleListRequest
	GetRoleListResponse        = system.GetRoleListResponse
	GetRoleParentRequest       = system.GetRoleParentRequest
	GetRoleParentResponse      = system.GetRoleParentResponse
	GetRoutesRequest           = system.GetRoutesRequest
	GetRoutesResponse          = system.GetRoutesResponse
	GetRuleContentRequest      = system.GetRuleContentRequest
	GetRuleContentResponse     = system.GetRuleContentResponse
	GetRuleListRequest         = system.GetRuleListRequest
	GetRuleListResponse        = system.GetRuleListResponse
	GetRuleParentRequest       = system.GetRuleParentRequest
	GetRuleParentResponse      = system.GetRuleParentResponse
	IsAccountExistRequest      = system.IsAccountExistRequest
	IsAccountExistResponse     = system.IsAccountExistResponse
	OperationLogData           = system.OperationLogData
	RoleData                   = system.RoleData
	RuleListData               = system.RuleListData
	SaveAccountRequest         = system.SaveAccountRequest
	SaveAccountResponse        = system.SaveAccountResponse
	SaveDeptRequest            = system.SaveDeptRequest
	SaveDeptResponse           = system.SaveDeptResponse
	SaveRoleRequest            = system.SaveRoleRequest
	SaveRoleResponse           = system.SaveRoleResponse
	SaveRuleRequest            = system.SaveRuleRequest
	SaveRuleResponse           = system.SaveRuleResponse
	UpStatusAccountRequest     = system.UpStatusAccountRequest
	UpStatusAccountResponse    = system.UpStatusAccountResponse
	UpStatusDeptRequest        = system.UpStatusDeptRequest
	UpStatusDeptResponse       = system.UpStatusDeptResponse
	UpStatusRoleRequest        = system.UpStatusRoleRequest
	UpStatusRoleResponse       = system.UpStatusRoleResponse
	UpStatusRuleRequest        = system.UpStatusRuleRequest
	UpStatusRuleResponse       = system.UpStatusRuleResponse

	DeptService interface {
		GetList(ctx context.Context, in *GetDeptListRequest, opts ...grpc.CallOption) (*GetDeptListResponse, error)
		Save(ctx context.Context, in *SaveDeptRequest, opts ...grpc.CallOption) (*SaveDeptResponse, error)
		UpState(ctx context.Context, in *UpStatusDeptRequest, opts ...grpc.CallOption) (*UpStatusDeptResponse, error)
		Del(ctx context.Context, in *DelDeptRequest, opts ...grpc.CallOption) (*DelDeptResponse, error)
		GetParent(ctx context.Context, in *GetDeptParentRequest, opts ...grpc.CallOption) (*GetDeptParentResponse, error)
	}

	defaultDeptService struct {
		cli zrpc.Client
	}
)

func NewDeptService(cli zrpc.Client) DeptService {
	return &defaultDeptService{
		cli: cli,
	}
}

func (m *defaultDeptService) GetList(ctx context.Context, in *GetDeptListRequest, opts ...grpc.CallOption) (*GetDeptListResponse, error) {
	client := system.NewDeptServiceClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultDeptService) Save(ctx context.Context, in *SaveDeptRequest, opts ...grpc.CallOption) (*SaveDeptResponse, error) {
	client := system.NewDeptServiceClient(m.cli.Conn())
	return client.Save(ctx, in, opts...)
}

func (m *defaultDeptService) UpState(ctx context.Context, in *UpStatusDeptRequest, opts ...grpc.CallOption) (*UpStatusDeptResponse, error) {
	client := system.NewDeptServiceClient(m.cli.Conn())
	return client.UpState(ctx, in, opts...)
}

func (m *defaultDeptService) Del(ctx context.Context, in *DelDeptRequest, opts ...grpc.CallOption) (*DelDeptResponse, error) {
	client := system.NewDeptServiceClient(m.cli.Conn())
	return client.Del(ctx, in, opts...)
}

func (m *defaultDeptService) GetParent(ctx context.Context, in *GetDeptParentRequest, opts ...grpc.CallOption) (*GetDeptParentResponse, error) {
	client := system.NewDeptServiceClient(m.cli.Conn())
	return client.GetParent(ctx, in, opts...)
}
