// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: develop.proto

package developservice

import (
	"context"

	"develop/develop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckedHaseTableRequest      = develop.CheckedHaseTableRequest
	CheckedHaseTableResponse     = develop.CheckedHaseTableResponse
	DelRequest                   = develop.DelRequest
	DelResponse                  = develop.DelResponse
	DelTplCodeRequest            = develop.DelTplCodeRequest
	DelTplCodeResponse           = develop.DelTplCodeResponse
	DevelopContentData           = develop.DevelopContentData
	DevelopContentList           = develop.DevelopContentList
	DevelopContentSearchList     = develop.DevelopContentSearchList
	DevelopFieldList             = develop.DevelopFieldList
	DevelopListData              = develop.DevelopListData
	DevelopMenuParentList        = develop.DevelopMenuParentList
	GetDbFieldData               = develop.GetDbFieldData
	GetDbfieldRequest            = develop.GetDbfieldRequest
	GetDbfieldResponse           = develop.GetDbfieldResponse
	GetDevelopContentRequest     = develop.GetDevelopContentRequest
	GetDevelopContentResponse    = develop.GetDevelopContentResponse
	GetDevelopListResponse       = develop.GetDevelopListResponse
	GetDevelopMenuParentRequest  = develop.GetDevelopMenuParentRequest
	GetDevelopMenuParentResponse = develop.GetDevelopMenuParentResponse
	GetGoVueDirRequest           = develop.GetGoVueDirRequest
	GetGoVueDirResponse          = develop.GetGoVueDirResponse
	GetListRequest               = develop.GetListRequest
	GetTableListRequest          = develop.GetTableListRequest
	GetTableListResponse         = develop.GetTableListResponse
	MarkTplCodeRequest           = develop.MarkTplCodeRequest
	MarkTplCodeResponse          = develop.MarkTplCodeResponse
	TableListData                = develop.TableListData
	UninstallCodeRequest         = develop.UninstallCodeRequest
	UninstallCodeResponse        = develop.UninstallCodeResponse
	UpCodeTableRequest           = develop.UpCodeTableRequest
	UpCodeTableResponse          = develop.UpCodeTableResponse
	UpStatusRequest              = develop.UpStatusRequest
	UpStatusResponse             = develop.UpStatusResponse

	DevelopService interface {
		GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetDevelopListResponse, error)
		GetContent(ctx context.Context, in *GetDevelopContentRequest, opts ...grpc.CallOption) (*GetDevelopContentResponse, error)
		UpStatus(ctx context.Context, in *UpStatusRequest, opts ...grpc.CallOption) (*UpStatusResponse, error)
		Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
		DelTplCode(ctx context.Context, in *DelTplCodeRequest, opts ...grpc.CallOption) (*DelTplCodeResponse, error)
		UninstallCode(ctx context.Context, in *UninstallCodeRequest, opts ...grpc.CallOption) (*UninstallCodeResponse, error)
		GetDbField(ctx context.Context, in *GetDbfieldRequest, opts ...grpc.CallOption) (*GetDbfieldResponse, error)
		GetMenuParent(ctx context.Context, in *GetDevelopMenuParentRequest, opts ...grpc.CallOption) (*GetDevelopMenuParentResponse, error)
		GetTableList(ctx context.Context, in *GetTableListRequest, opts ...grpc.CallOption) (*GetTableListResponse, error)
		CheckedHaseTable(ctx context.Context, in *CheckedHaseTableRequest, opts ...grpc.CallOption) (*CheckedHaseTableResponse, error)
		UpCodeTable(ctx context.Context, in *UpCodeTableRequest, opts ...grpc.CallOption) (*UpCodeTableResponse, error)
		GetGoVueDir(ctx context.Context, in *GetGoVueDirRequest, opts ...grpc.CallOption) (*GetGoVueDirResponse, error)
		MarkTplCode(ctx context.Context, in *MarkTplCodeRequest, opts ...grpc.CallOption) (*MarkTplCodeResponse, error)
	}

	defaultDevelopService struct {
		cli zrpc.Client
	}
)

func NewDevelopService(cli zrpc.Client) DevelopService {
	return &defaultDevelopService{
		cli: cli,
	}
}

func (m *defaultDevelopService) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetDevelopListResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultDevelopService) GetContent(ctx context.Context, in *GetDevelopContentRequest, opts ...grpc.CallOption) (*GetDevelopContentResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.GetContent(ctx, in, opts...)
}

func (m *defaultDevelopService) UpStatus(ctx context.Context, in *UpStatusRequest, opts ...grpc.CallOption) (*UpStatusResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.UpStatus(ctx, in, opts...)
}

func (m *defaultDevelopService) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.Del(ctx, in, opts...)
}

func (m *defaultDevelopService) DelTplCode(ctx context.Context, in *DelTplCodeRequest, opts ...grpc.CallOption) (*DelTplCodeResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.DelTplCode(ctx, in, opts...)
}

func (m *defaultDevelopService) UninstallCode(ctx context.Context, in *UninstallCodeRequest, opts ...grpc.CallOption) (*UninstallCodeResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.UninstallCode(ctx, in, opts...)
}

func (m *defaultDevelopService) GetDbField(ctx context.Context, in *GetDbfieldRequest, opts ...grpc.CallOption) (*GetDbfieldResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.GetDbField(ctx, in, opts...)
}

func (m *defaultDevelopService) GetMenuParent(ctx context.Context, in *GetDevelopMenuParentRequest, opts ...grpc.CallOption) (*GetDevelopMenuParentResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.GetMenuParent(ctx, in, opts...)
}

func (m *defaultDevelopService) GetTableList(ctx context.Context, in *GetTableListRequest, opts ...grpc.CallOption) (*GetTableListResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.GetTableList(ctx, in, opts...)
}

func (m *defaultDevelopService) CheckedHaseTable(ctx context.Context, in *CheckedHaseTableRequest, opts ...grpc.CallOption) (*CheckedHaseTableResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.CheckedHaseTable(ctx, in, opts...)
}

func (m *defaultDevelopService) UpCodeTable(ctx context.Context, in *UpCodeTableRequest, opts ...grpc.CallOption) (*UpCodeTableResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.UpCodeTable(ctx, in, opts...)
}

func (m *defaultDevelopService) GetGoVueDir(ctx context.Context, in *GetGoVueDirRequest, opts ...grpc.CallOption) (*GetGoVueDirResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.GetGoVueDir(ctx, in, opts...)
}

func (m *defaultDevelopService) MarkTplCode(ctx context.Context, in *MarkTplCodeRequest, opts ...grpc.CallOption) (*MarkTplCodeResponse, error) {
	client := develop.NewDevelopServiceClient(m.cli.Conn())
	return client.MarkTplCode(ctx, in, opts...)
}
