// 声明 proto 使用的语法版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.11
// source: common.proto

// proto 包名

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取验证码请求
type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 验证码类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *GetCaptchaRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets      []string               `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

// 嵌套类型
// 您可以在其他消息类型中定义和使用消息类型，如以下示例所示：Result 消息在 SearchResponse
// 消息中定义：
// 获取验证码响应
// 验证码数据
type GetCaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`             // 验证码ID
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                  // id
	ExpireTime    int64                  `protobuf:"varint,3,opt,name=expireTime,proto3" json:"expireTime,omitempty"` // 过期时间戳
	Img           string                 `protobuf:"bytes,4,opt,name=img,proto3" json:"img,omitempty"`                // 验证码图片base64编码
	Show          bool                   `protobuf:"varint,5,opt,name=show,proto3" json:"show,omitempty"`             // 是否需要展示验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaResponse) Reset() {
	*x = GetCaptchaResponse{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResponse) ProtoMessage() {}

func (x *GetCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResponse.ProtoReflect.Descriptor instead.
func (*GetCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *GetCaptchaResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCaptchaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCaptchaResponse) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *GetCaptchaResponse) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *GetCaptchaResponse) GetShow() bool {
	if x != nil {
		return x.Show
	}
	return false
}

// 获取菜单数据
type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RouteId       uint64                 `protobuf:"varint,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMenuRequest) GetRouteId() uint64 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 菜单数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// *
// 获取首页快速编辑数据
type GetQuickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickRequest) Reset() {
	*x = GetQuickRequest{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickRequest) ProtoMessage() {}

func (x *GetQuickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickRequest.ProtoReflect.Descriptor instead.
func (*GetQuickRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

type GetQuickRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         map[string]string      `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickRow) Reset() {
	*x = GetQuickRow{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickRow) ProtoMessage() {}

func (x *GetQuickRow) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickRow.ProtoReflect.Descriptor instead.
func (*GetQuickRow) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *GetQuickRow) GetPairs() map[string]string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type GetQuickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GetQuickRow         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 快速数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuickResponse) Reset() {
	*x = GetQuickResponse{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuickResponse) ProtoMessage() {}

func (x *GetQuickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuickResponse.ProtoReflect.Descriptor instead.
func (*GetQuickResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *GetQuickResponse) GetData() []*GetQuickRow {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"'\n" +
	"\x11GetCaptchaRequest\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"L\n" +
	"\x06Result\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsnippets\x18\x03 \x03(\tR\bsnippets\"~\n" +
	"\x12GetCaptchaResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x04R\x04code\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x03 \x01(\x03R\n" +
	"expireTime\x12\x10\n" +
	"\x03img\x18\x04 \x01(\tR\x03img\x12\x12\n" +
	"\x04show\x18\x05 \x01(\bR\x04show\"D\n" +
	"\x0eGetMenuRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\x04R\arouteId\"%\n" +
	"\x0fGetMenuResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x11\n" +
	"\x0fGetQuickRequest\"}\n" +
	"\vGetQuickRow\x124\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1e.common.GetQuickRow.PairsEntryR\x05pairs\x1a8\n" +
	"\n" +
	"PairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x10GetQuickResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.common.GetQuickRowR\x04data2\x90\x01\n" +
	"\rCommonService\x12C\n" +
	"\n" +
	"GetCaptcha\x12\x19.common.GetCaptchaRequest\x1a\x1a.common.GetCaptchaResponse\x12:\n" +
	"\aGetMenu\x12\x16.common.GetMenuRequest\x1a\x17.common.GetMenuResponse2U\n" +
	"\x10DashboardService\x12A\n" +
	"\fGetDashboard\x12\x17.common.GetQuickRequest\x1a\x18.common.GetQuickResponseB\n" +
	"Z\b./commonb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil),  // 0: common.GetCaptchaRequest
	(*Result)(nil),             // 1: common.Result
	(*GetCaptchaResponse)(nil), // 2: common.GetCaptchaResponse
	(*GetMenuRequest)(nil),     // 3: common.GetMenuRequest
	(*GetMenuResponse)(nil),    // 4: common.GetMenuResponse
	(*GetQuickRequest)(nil),    // 5: common.GetQuickRequest
	(*GetQuickRow)(nil),        // 6: common.GetQuickRow
	(*GetQuickResponse)(nil),   // 7: common.GetQuickResponse
	nil,                        // 8: common.GetQuickRow.PairsEntry
}
var file_common_proto_depIdxs = []int32{
	8, // 0: common.GetQuickRow.pairs:type_name -> common.GetQuickRow.PairsEntry
	6, // 1: common.GetQuickResponse.data:type_name -> common.GetQuickRow
	0, // 2: common.CommonService.GetCaptcha:input_type -> common.GetCaptchaRequest
	3, // 3: common.CommonService.GetMenu:input_type -> common.GetMenuRequest
	5, // 4: common.DashboardService.GetDashboard:input_type -> common.GetQuickRequest
	2, // 5: common.CommonService.GetCaptcha:output_type -> common.GetCaptchaResponse
	4, // 6: common.CommonService.GetMenu:output_type -> common.GetMenuResponse
	7, // 7: common.DashboardService.GetDashboard:output_type -> common.GetQuickResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
