// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"system/internal/logic/ruleservice"
	"system/internal/svc"
	"system/system"
)

type RuleServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedRuleServiceServer
}

func NewRuleServiceServer(svcCtx *svc.ServiceContext) *RuleServiceServer {
	return &RuleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RuleServiceServer) GetList(ctx context.Context, in *system.GetRuleListRequest) (*system.GetRuleListResponse, error) {
	l := ruleservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *RuleServiceServer) Save(ctx context.Context, in *system.SaveRuleRequest) (*system.SaveRuleResponse, error) {
	l := ruleservicelogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

func (s *RuleServiceServer) UpStatus(ctx context.Context, in *system.UpStatusRuleRequest) (*system.UpStatusRuleResponse, error) {
	l := ruleservicelogic.NewUpStatusLogic(ctx, s.svcCtx)
	return l.UpStatus(in)
}

func (s *RuleServiceServer) Del(ctx context.Context, in *system.DelRuleRequest) (*system.DelRuleResponse, error) {
	l := ruleservicelogic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *RuleServiceServer) GetContent(ctx context.Context, in *system.GetRuleContentRequest) (*system.GetRuleContentResponse, error) {
	l := ruleservicelogic.NewGetContentLogic(ctx, s.svcCtx)
	return l.GetContent(in)
}

func (s *RuleServiceServer) GetParent(ctx context.Context, in *system.GetRuleParentRequest) (*system.GetRuleParentResponse, error) {
	l := ruleservicelogic.NewGetParentLogic(ctx, s.svcCtx)
	return l.GetParent(in)
}

func (s *RuleServiceServer) GetRoutes(ctx context.Context, in *system.GetRoutesRequest) (*system.GetRoutesResponse, error) {
	l := ruleservicelogic.NewGetRoutesLogic(ctx, s.svcCtx)
	return l.GetRoutes(in)
}
