// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	common "admin/internal/handler/common"
	config "admin/internal/handler/config"
	system "admin/internal/handler/system"
	user "admin/internal/handler/user"
	"admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/common/getCaptcha",
				Handler: common.GetCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/common/getMenu",
				Handler: common.GetMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/common/getQuick",
				Handler: common.GetQuickHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/common/saveQuick",
				Handler: common.SaveQuickHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/config/categoryAll",
				Handler: config.GetCategoryAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/categoryDetail",
				Handler: config.GetCategoryDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/categoryList",
				Handler: config.GetCategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/createCategory",
				Handler: config.CreateCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/deleteCategory",
				Handler: config.DeleteCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/updateCategory",
				Handler: config.UpdateCategoryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/config/createConfig",
				Handler: config.CreateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/deleteConfig",
				Handler: config.DeleteConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigByCategory",
				Handler: config.GetConfigByCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigDetail",
				Handler: config.GetConfigDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigList",
				Handler: config.GetConfigListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigValue",
				Handler: config.GetConfigValueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/saveConfigValue",
				Handler: config.SaveConfigValueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/updateConfig",
				Handler: config.UpdateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/updateConfigStatus",
				Handler: config.UpdateConfigStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/system/getLogin",
				Handler: system.GetLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/getRuleList",
				Handler: system.GetRuleListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/getUserInfo",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
