// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	common "admin/internal/handler/common"
	config "admin/internal/handler/config"
	config_category "admin/internal/handler/config_category"
	dept "admin/internal/handler/dept"
	log "admin/internal/handler/log"
	rule "admin/internal/handler/rule"
	user "admin/internal/handler/user"
	"admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/common/getCaptcha",
				Handler: common.GetCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/common/getMenu",
				Handler: common.GetMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/common/getQuick",
				Handler: common.GetQuickHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/common/saveQuick",
				Handler: common.SaveQuickHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/config/createConfig",
				Handler: config.CreateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/deleteConfig",
				Handler: config.DeleteConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigByCategory",
				Handler: config.GetConfigByCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigDetail",
				Handler: config.GetConfigDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigList",
				Handler: config.GetConfigListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/getConfigValue",
				Handler: config.GetConfigValueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/saveConfigValue",
				Handler: config.SaveConfigValueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/updateConfig",
				Handler: config.UpdateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/updateConfigStatus",
				Handler: config.UpdateConfigStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/config/categoryAll",
				Handler: config_category.GetCategoryAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/categoryDetail",
				Handler: config_category.GetCategoryDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/config/categoryList",
				Handler: config_category.GetCategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/createCategory",
				Handler: config_category.CreateCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/deleteCategory",
				Handler: config_category.DeleteCategoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/config/updateCategory",
				Handler: config_category.UpdateCategoryHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/dept/del",
				Handler: dept.DelDeptHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dept/getList",
				Handler: dept.GetDeptListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dept/getParent",
				Handler: dept.GetDeptParentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dept/save",
				Handler: dept.SaveDeptHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dept/upStatus",
				Handler: dept.UpStatusDeptHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/system"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/log/getLogin",
				Handler: log.GetLoginHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/system"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/rule/del",
				Handler: rule.DelRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rule/getContent",
				Handler: rule.GetRuleContentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rule/getList",
				Handler: rule.GetRuleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rule/getParent",
				Handler: rule.GetRuleParentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/rule/getRoutes",
				Handler: rule.GetRoutesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rule/save",
				Handler: rule.SaveRuleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rule/upStatus",
				Handler: rule.UpStatusRuleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/system"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/getUserInfo",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin"),
		rest.WithTimeout(3000*time.Millisecond),
	)
}
