// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"system/internal/logic/roleservice"
	"system/internal/svc"
	"system/system"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleServiceServer) GetList(ctx context.Context, in *system.GetRoleListRequest) (*system.GetRoleListResponse, error) {
	l := roleservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *RoleServiceServer) Save(ctx context.Context, in *system.SaveRoleRequest) (*system.SaveRoleResponse, error) {
	l := roleservicelogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

func (s *RoleServiceServer) UpStatus(ctx context.Context, in *system.UpStatusRoleRequest) (*system.UpStatusRoleResponse, error) {
	l := roleservicelogic.NewUpStatusLogic(ctx, s.svcCtx)
	return l.UpStatus(in)
}

func (s *RoleServiceServer) Del(ctx context.Context, in *system.DelRoleRequest) (*system.DelRoleResponse, error) {
	l := roleservicelogic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *RoleServiceServer) GetParent(ctx context.Context, in *system.GetRoleParentRequest) (*system.GetRoleParentResponse, error) {
	l := roleservicelogic.NewGetParentLogic(ctx, s.svcCtx)
	return l.GetParent(in)
}

func (s *RoleServiceServer) GetMenuList(ctx context.Context, in *system.GetMenuListRequest) (*system.GetMenuListResponse, error) {
	l := roleservicelogic.NewGetMenuListLogic(ctx, s.svcCtx)
	return l.GetMenuList(in)
}
