// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package server

import (
	"context"

	"common/common"
	"common/internal/logic/dashboardservice"
	"common/internal/svc"
)

type DashboardServiceServer struct {
	svcCtx *svc.ServiceContext
	common.UnimplementedDashboardServiceServer
}

func NewDashboardServiceServer(svcCtx *svc.ServiceContext) *DashboardServiceServer {
	return &DashboardServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DashboardServiceServer) GetQuick(ctx context.Context, in *common.GetQuickRequest) (*common.GetQuickResponse, error) {
	l := dashboardservicelogic.NewGetQuickLogic(ctx, s.svcCtx)
	return l.GetQuick(in)
}

func (s *DashboardServiceServer) SaveQuick(ctx context.Context, in *common.SaveQuickRequest) (*common.SaveQuickResponse, error) {
	l := dashboardservicelogic.NewSaveQuickLogic(ctx, s.svcCtx)
	return l.SaveQuick(in)
}
