// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package server

import (
	"context"

	"common/common"
	"common/internal/logic/dashboardservice"
	"common/internal/svc"
)

type DashboardServiceServer struct {
	svcCtx *svc.ServiceContext
	common.UnimplementedDashboardServiceServer
}

func NewDashboardServiceServer(svcCtx *svc.ServiceContext) *DashboardServiceServer {
	return &DashboardServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DashboardServiceServer) GetDashboard(ctx context.Context, in *common.GetQuickRequest) (*common.GetQuickResponse, error) {
	l := dashboardservicelogic.NewGetDashboardLogic(ctx, s.svcCtx)
	return l.GetDashboard(in)
}
