// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.11
// source: configcenter.proto

package configcenter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigCategoryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryKey   string                 `protobuf:"bytes,2,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	CategoryName  string                 `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	IsSystem      int32                  `protobuf:"varint,6,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	CreateTime    string                 `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigCategoryData) Reset() {
	*x = ConfigCategoryData{}
	mi := &file_configcenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigCategoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCategoryData) ProtoMessage() {}

func (x *ConfigCategoryData) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCategoryData.ProtoReflect.Descriptor instead.
func (*ConfigCategoryData) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigCategoryData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigCategoryData) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *ConfigCategoryData) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ConfigCategoryData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigCategoryData) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ConfigCategoryData) GetIsSystem() int32 {
	if x != nil {
		return x.IsSystem
	}
	return 0
}

func (x *ConfigCategoryData) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *ConfigCategoryData) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type GetCategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryListRequest) Reset() {
	*x = GetCategoryListRequest{}
	mi := &file_configcenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryListRequest) ProtoMessage() {}

func (x *GetCategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryListRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryListRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoryListRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *GetCategoryListRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *GetCategoryListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCategoryListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigCategoryData  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryListResponse) Reset() {
	*x = GetCategoryListResponse{}
	mi := &file_configcenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryListResponse) ProtoMessage() {}

func (x *GetCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryListResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryListResponse) GetItems() []*ConfigCategoryData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCategoryListResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCategoryListResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCategoryListResponse) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCategoryAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryAllRequest) Reset() {
	*x = GetCategoryAllRequest{}
	mi := &file_configcenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryAllRequest) ProtoMessage() {}

func (x *GetCategoryAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryAllRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryAllRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{3}
}

type GetCategoryAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigCategoryData  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryAllResponse) Reset() {
	*x = GetCategoryAllResponse{}
	mi := &file_configcenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryAllResponse) ProtoMessage() {}

func (x *GetCategoryAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryAllResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryAllResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{4}
}

func (x *GetCategoryAllResponse) GetItems() []*ConfigCategoryData {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetCategoryDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryDetailRequest) Reset() {
	*x = GetCategoryDetailRequest{}
	mi := &file_configcenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryDetailRequest) ProtoMessage() {}

func (x *GetCategoryDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryDetailRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryDetailRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{5}
}

func (x *GetCategoryDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ConfigCategoryData    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryDetailResponse) Reset() {
	*x = GetCategoryDetailResponse{}
	mi := &file_configcenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryDetailResponse) ProtoMessage() {}

func (x *GetCategoryDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryDetailResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryDetailResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{6}
}

func (x *GetCategoryDetailResponse) GetData() *ConfigCategoryData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_configcenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCategoryRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *CreateCategoryRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CreateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_configcenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCategoryResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_configcenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *UpdateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCategoryRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_configcenter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{10}
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_configcenter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_configcenter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{12}
}

type ConfigOptionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigOptionItem) Reset() {
	*x = ConfigOptionItem{}
	mi := &file_configcenter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigOptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigOptionItem) ProtoMessage() {}

func (x *ConfigOptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigOptionItem.ProtoReflect.Descriptor instead.
func (*ConfigOptionItem) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigOptionItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigOptionItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ConfigItemData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryKey    string                 `protobuf:"bytes,2,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	ConfigKey      string                 `protobuf:"bytes,3,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	ConfigName     string                 `protobuf:"bytes,4,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigType     string                 `protobuf:"bytes,5,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ConfigValue    string                 `protobuf:"bytes,6,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	DefaultValue   string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Options        []*ConfigOptionItem    `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty"`
	ValidationRule string                 `protobuf:"bytes,10,opt,name=validation_rule,json=validationRule,proto3" json:"validation_rule,omitempty"`
	Placeholder    string                 `protobuf:"bytes,11,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	IsRequired     int32                  `protobuf:"varint,12,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	IsSecret       int32                  `protobuf:"varint,13,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	SortOrder      int32                  `protobuf:"varint,14,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status         int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTime    string                 `protobuf:"bytes,16,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime    string                 `protobuf:"bytes,17,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigItemData) Reset() {
	*x = ConfigItemData{}
	mi := &file_configcenter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemData) ProtoMessage() {}

func (x *ConfigItemData) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemData.ProtoReflect.Descriptor instead.
func (*ConfigItemData) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigItemData) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfigItemData) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *ConfigItemData) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ConfigItemData) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ConfigItemData) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ConfigItemData) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

func (x *ConfigItemData) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigItemData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigItemData) GetOptions() []*ConfigOptionItem {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigItemData) GetValidationRule() string {
	if x != nil {
		return x.ValidationRule
	}
	return ""
}

func (x *ConfigItemData) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *ConfigItemData) GetIsRequired() int32 {
	if x != nil {
		return x.IsRequired
	}
	return 0
}

func (x *ConfigItemData) GetIsSecret() int32 {
	if x != nil {
		return x.IsSecret
	}
	return 0
}

func (x *ConfigItemData) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ConfigItemData) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ConfigItemData) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *ConfigItemData) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type GetConfigListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	ConfigKey     string                 `protobuf:"bytes,2,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	ConfigName    string                 `protobuf:"bytes,3,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigListRequest) Reset() {
	*x = GetConfigListRequest{}
	mi := &file_configcenter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigListRequest) ProtoMessage() {}

func (x *GetConfigListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigListRequest.ProtoReflect.Descriptor instead.
func (*GetConfigListRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{15}
}

func (x *GetConfigListRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *GetConfigListRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *GetConfigListRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *GetConfigListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetConfigListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetConfigListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetConfigListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigItemData      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint64                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint64                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigListResponse) Reset() {
	*x = GetConfigListResponse{}
	mi := &file_configcenter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigListResponse) ProtoMessage() {}

func (x *GetConfigListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigListResponse.ProtoReflect.Descriptor instead.
func (*GetConfigListResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{16}
}

func (x *GetConfigListResponse) GetItems() []*ConfigItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetConfigListResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetConfigListResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetConfigListResponse) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetConfigByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigByCategoryRequest) Reset() {
	*x = GetConfigByCategoryRequest{}
	mi := &file_configcenter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigByCategoryRequest) ProtoMessage() {}

func (x *GetConfigByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetConfigByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{17}
}

func (x *GetConfigByCategoryRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

type GetConfigByCategoryResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CategoryName        string                 `protobuf:"bytes,1,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryDescription string                 `protobuf:"bytes,2,opt,name=category_description,json=categoryDescription,proto3" json:"category_description,omitempty"`
	Items               []*ConfigItemData      `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetConfigByCategoryResponse) Reset() {
	*x = GetConfigByCategoryResponse{}
	mi := &file_configcenter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigByCategoryResponse) ProtoMessage() {}

func (x *GetConfigByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigByCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetConfigByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{18}
}

func (x *GetConfigByCategoryResponse) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *GetConfigByCategoryResponse) GetCategoryDescription() string {
	if x != nil {
		return x.CategoryDescription
	}
	return ""
}

func (x *GetConfigByCategoryResponse) GetItems() []*ConfigItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetConfigDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigDetailRequest) Reset() {
	*x = GetConfigDetailRequest{}
	mi := &file_configcenter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigDetailRequest) ProtoMessage() {}

func (x *GetConfigDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigDetailRequest.ProtoReflect.Descriptor instead.
func (*GetConfigDetailRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{19}
}

func (x *GetConfigDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetConfigDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ConfigItemData        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigDetailResponse) Reset() {
	*x = GetConfigDetailResponse{}
	mi := &file_configcenter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigDetailResponse) ProtoMessage() {}

func (x *GetConfigDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigDetailResponse.ProtoReflect.Descriptor instead.
func (*GetConfigDetailResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{20}
}

func (x *GetConfigDetailResponse) GetData() *ConfigItemData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey    string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	ConfigKey      string                 `protobuf:"bytes,2,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	ConfigName     string                 `protobuf:"bytes,3,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigType     string                 `protobuf:"bytes,4,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ConfigValue    string                 `protobuf:"bytes,5,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	DefaultValue   string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Options        string                 `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	ValidationRule string                 `protobuf:"bytes,9,opt,name=validation_rule,json=validationRule,proto3" json:"validation_rule,omitempty"`
	Placeholder    string                 `protobuf:"bytes,10,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	IsRequired     int32                  `protobuf:"varint,11,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	IsSecret       int32                  `protobuf:"varint,12,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	SortOrder      int32                  `protobuf:"varint,13,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status         int32                  `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConfigRequest) Reset() {
	*x = CreateConfigRequest{}
	mi := &file_configcenter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigRequest) ProtoMessage() {}

func (x *CreateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigRequest.ProtoReflect.Descriptor instead.
func (*CreateConfigRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{21}
}

func (x *CreateConfigRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *CreateConfigRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *CreateConfigRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *CreateConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *CreateConfigRequest) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

func (x *CreateConfigRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *CreateConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateConfigRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *CreateConfigRequest) GetValidationRule() string {
	if x != nil {
		return x.ValidationRule
	}
	return ""
}

func (x *CreateConfigRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *CreateConfigRequest) GetIsRequired() int32 {
	if x != nil {
		return x.IsRequired
	}
	return 0
}

func (x *CreateConfigRequest) GetIsSecret() int32 {
	if x != nil {
		return x.IsSecret
	}
	return 0
}

func (x *CreateConfigRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateConfigRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfigResponse) Reset() {
	*x = CreateConfigResponse{}
	mi := &file_configcenter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigResponse) ProtoMessage() {}

func (x *CreateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigResponse.ProtoReflect.Descriptor instead.
func (*CreateConfigResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{22}
}

func (x *CreateConfigResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryKey    string                 `protobuf:"bytes,2,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	ConfigKey      string                 `protobuf:"bytes,3,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	ConfigName     string                 `protobuf:"bytes,4,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"`
	ConfigType     string                 `protobuf:"bytes,5,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ConfigValue    string                 `protobuf:"bytes,6,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	DefaultValue   string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Options        string                 `protobuf:"bytes,9,opt,name=options,proto3" json:"options,omitempty"`
	ValidationRule string                 `protobuf:"bytes,10,opt,name=validation_rule,json=validationRule,proto3" json:"validation_rule,omitempty"`
	Placeholder    string                 `protobuf:"bytes,11,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	IsRequired     int32                  `protobuf:"varint,12,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	IsSecret       int32                  `protobuf:"varint,13,opt,name=is_secret,json=isSecret,proto3" json:"is_secret,omitempty"`
	SortOrder      int32                  `protobuf:"varint,14,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status         int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_configcenter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateConfigRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateConfigRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *UpdateConfigRequest) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

func (x *UpdateConfigRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *UpdateConfigRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateConfigRequest) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

func (x *UpdateConfigRequest) GetValidationRule() string {
	if x != nil {
		return x.ValidationRule
	}
	return ""
}

func (x *UpdateConfigRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *UpdateConfigRequest) GetIsRequired() int32 {
	if x != nil {
		return x.IsRequired
	}
	return 0
}

func (x *UpdateConfigRequest) GetIsSecret() int32 {
	if x != nil {
		return x.IsSecret
	}
	return 0
}

func (x *UpdateConfigRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateConfigRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_configcenter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{24}
}

type DeleteConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigRequest) Reset() {
	*x = DeleteConfigRequest{}
	mi := &file_configcenter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigRequest) ProtoMessage() {}

func (x *DeleteConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteConfigRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConfigResponse) Reset() {
	*x = DeleteConfigResponse{}
	mi := &file_configcenter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfigResponse) ProtoMessage() {}

func (x *DeleteConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfigResponse.ProtoReflect.Descriptor instead.
func (*DeleteConfigResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{26}
}

type UpdateConfigStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigStatusRequest) Reset() {
	*x = UpdateConfigStatusRequest{}
	mi := &file_configcenter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigStatusRequest) ProtoMessage() {}

func (x *UpdateConfigStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigStatusRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateConfigStatusRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateConfigStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateConfigStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigStatusResponse) Reset() {
	*x = UpdateConfigStatusResponse{}
	mi := &file_configcenter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigStatusResponse) ProtoMessage() {}

func (x *UpdateConfigStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigStatusResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{28}
}

type SaveConfigValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	ConfigValues  map[string]string      `protobuf:"bytes,2,rep,name=config_values,json=configValues,proto3" json:"config_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigValueRequest) Reset() {
	*x = SaveConfigValueRequest{}
	mi := &file_configcenter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigValueRequest) ProtoMessage() {}

func (x *SaveConfigValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigValueRequest.ProtoReflect.Descriptor instead.
func (*SaveConfigValueRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{29}
}

func (x *SaveConfigValueRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

func (x *SaveConfigValueRequest) GetConfigValues() map[string]string {
	if x != nil {
		return x.ConfigValues
	}
	return nil
}

type SaveConfigValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigValueResponse) Reset() {
	*x = SaveConfigValueResponse{}
	mi := &file_configcenter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigValueResponse) ProtoMessage() {}

func (x *SaveConfigValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigValueResponse.ProtoReflect.Descriptor instead.
func (*SaveConfigValueResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{30}
}

type GetConfigValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryKey   string                 `protobuf:"bytes,1,opt,name=category_key,json=categoryKey,proto3" json:"category_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigValueRequest) Reset() {
	*x = GetConfigValueRequest{}
	mi := &file_configcenter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigValueRequest) ProtoMessage() {}

func (x *GetConfigValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigValueRequest.ProtoReflect.Descriptor instead.
func (*GetConfigValueRequest) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{31}
}

func (x *GetConfigValueRequest) GetCategoryKey() string {
	if x != nil {
		return x.CategoryKey
	}
	return ""
}

type ConfigValueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigKey     string                 `protobuf:"bytes,1,opt,name=config_key,json=configKey,proto3" json:"config_key,omitempty"`
	ConfigValue   string                 `protobuf:"bytes,2,opt,name=config_value,json=configValue,proto3" json:"config_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValueItem) Reset() {
	*x = ConfigValueItem{}
	mi := &file_configcenter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValueItem) ProtoMessage() {}

func (x *ConfigValueItem) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValueItem.ProtoReflect.Descriptor instead.
func (*ConfigValueItem) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{32}
}

func (x *ConfigValueItem) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ConfigValueItem) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

type GetConfigValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigValueItem     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigValueResponse) Reset() {
	*x = GetConfigValueResponse{}
	mi := &file_configcenter_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigValueResponse) ProtoMessage() {}

func (x *GetConfigValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configcenter_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigValueResponse.ProtoReflect.Descriptor instead.
func (*GetConfigValueResponse) Descriptor() ([]byte, []int) {
	return file_configcenter_proto_rawDescGZIP(), []int{33}
}

func (x *GetConfigValueResponse) GetItems() []*ConfigValueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_configcenter_proto protoreflect.FileDescriptor

const file_configcenter_proto_rawDesc = "" +
	"\n" +
	"\x12configcenter.proto\x12\fconfigcenter\"\x8c\x02\n" +
	"\x12ConfigCategoryData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fcategory_key\x18\x02 \x01(\tR\vcategoryKey\x12#\n" +
	"\rcategory_name\x18\x03 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x1b\n" +
	"\tis_system\x18\x06 \x01(\x05R\bisSystem\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\tR\n" +
	"updateTime\"\x91\x01\n" +
	"\x16GetCategoryListRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x98\x01\n" +
	"\x17GetCategoryListResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .configcenter.ConfigCategoryDataR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x04R\bpageSize\"\x17\n" +
	"\x15GetCategoryAllRequest\"P\n" +
	"\x16GetCategoryAllResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .configcenter.ConfigCategoryDataR\x05items\"*\n" +
	"\x18GetCategoryDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"Q\n" +
	"\x19GetCategoryDetailResponse\x124\n" +
	"\x04data\x18\x01 \x01(\v2 .configcenter.ConfigCategoryDataR\x04data\"\xa0\x01\n" +
	"\x15CreateCategoryRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"(\n" +
	"\x16CreateCategoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x8d\x01\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"\x18\n" +
	"\x16UpdateCategoryResponse\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x18\n" +
	"\x16DeleteCategoryResponse\">\n" +
	"\x10ConfigOptionItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xce\x04\n" +
	"\x0eConfigItemData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fcategory_key\x18\x02 \x01(\tR\vcategoryKey\x12\x1d\n" +
	"\n" +
	"config_key\x18\x03 \x01(\tR\tconfigKey\x12\x1f\n" +
	"\vconfig_name\x18\x04 \x01(\tR\n" +
	"configName\x12\x1f\n" +
	"\vconfig_type\x18\x05 \x01(\tR\n" +
	"configType\x12!\n" +
	"\fconfig_value\x18\x06 \x01(\tR\vconfigValue\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x128\n" +
	"\aoptions\x18\t \x03(\v2\x1e.configcenter.ConfigOptionItemR\aoptions\x12'\n" +
	"\x0fvalidation_rule\x18\n" +
	" \x01(\tR\x0evalidationRule\x12 \n" +
	"\vplaceholder\x18\v \x01(\tR\vplaceholder\x12\x1f\n" +
	"\vis_required\x18\f \x01(\x05R\n" +
	"isRequired\x12\x1b\n" +
	"\tis_secret\x18\r \x01(\x05R\bisSecret\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x0e \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12!\n" +
	"\fcreated_time\x18\x10 \x01(\tR\vcreatedTime\x12!\n" +
	"\fupdated_time\x18\x11 \x01(\tR\vupdatedTime\"\xc2\x01\n" +
	"\x14GetConfigListRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12\x1d\n" +
	"\n" +
	"config_key\x18\x02 \x01(\tR\tconfigKey\x12\x1f\n" +
	"\vconfig_name\x18\x03 \x01(\tR\n" +
	"configName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x92\x01\n" +
	"\x15GetConfigListResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.configcenter.ConfigItemDataR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x04R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x04R\bpageSize\"?\n" +
	"\x1aGetConfigByCategoryRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\"\xa9\x01\n" +
	"\x1bGetConfigByCategoryResponse\x12#\n" +
	"\rcategory_name\x18\x01 \x01(\tR\fcategoryName\x121\n" +
	"\x14category_description\x18\x02 \x01(\tR\x13categoryDescription\x122\n" +
	"\x05items\x18\x03 \x03(\v2\x1c.configcenter.ConfigItemDataR\x05items\"(\n" +
	"\x16GetConfigDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"K\n" +
	"\x17GetConfigDetailResponse\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.configcenter.ConfigItemDataR\x04data\"\xdd\x03\n" +
	"\x13CreateConfigRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12\x1d\n" +
	"\n" +
	"config_key\x18\x02 \x01(\tR\tconfigKey\x12\x1f\n" +
	"\vconfig_name\x18\x03 \x01(\tR\n" +
	"configName\x12\x1f\n" +
	"\vconfig_type\x18\x04 \x01(\tR\n" +
	"configType\x12!\n" +
	"\fconfig_value\x18\x05 \x01(\tR\vconfigValue\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x18\n" +
	"\aoptions\x18\b \x01(\tR\aoptions\x12'\n" +
	"\x0fvalidation_rule\x18\t \x01(\tR\x0evalidationRule\x12 \n" +
	"\vplaceholder\x18\n" +
	" \x01(\tR\vplaceholder\x12\x1f\n" +
	"\vis_required\x18\v \x01(\x05R\n" +
	"isRequired\x12\x1b\n" +
	"\tis_secret\x18\f \x01(\x05R\bisSecret\x12\x1d\n" +
	"\n" +
	"sort_order\x18\r \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x0e \x01(\x05R\x06status\"&\n" +
	"\x14CreateConfigResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xed\x03\n" +
	"\x13UpdateConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fcategory_key\x18\x02 \x01(\tR\vcategoryKey\x12\x1d\n" +
	"\n" +
	"config_key\x18\x03 \x01(\tR\tconfigKey\x12\x1f\n" +
	"\vconfig_name\x18\x04 \x01(\tR\n" +
	"configName\x12\x1f\n" +
	"\vconfig_type\x18\x05 \x01(\tR\n" +
	"configType\x12!\n" +
	"\fconfig_value\x18\x06 \x01(\tR\vconfigValue\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x18\n" +
	"\aoptions\x18\t \x01(\tR\aoptions\x12'\n" +
	"\x0fvalidation_rule\x18\n" +
	" \x01(\tR\x0evalidationRule\x12 \n" +
	"\vplaceholder\x18\v \x01(\tR\vplaceholder\x12\x1f\n" +
	"\vis_required\x18\f \x01(\x05R\n" +
	"isRequired\x12\x1b\n" +
	"\tis_secret\x18\r \x01(\x05R\bisSecret\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x0e \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\"\x16\n" +
	"\x14UpdateConfigResponse\"%\n" +
	"\x13DeleteConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x16\n" +
	"\x14DeleteConfigResponse\"C\n" +
	"\x19UpdateConfigStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x1c\n" +
	"\x1aUpdateConfigStatusResponse\"\xd9\x01\n" +
	"\x16SaveConfigValueRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\x12[\n" +
	"\rconfig_values\x18\x02 \x03(\v26.configcenter.SaveConfigValueRequest.ConfigValuesEntryR\fconfigValues\x1a?\n" +
	"\x11ConfigValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17SaveConfigValueResponse\":\n" +
	"\x15GetConfigValueRequest\x12!\n" +
	"\fcategory_key\x18\x01 \x01(\tR\vcategoryKey\"S\n" +
	"\x0fConfigValueItem\x12\x1d\n" +
	"\n" +
	"config_key\x18\x01 \x01(\tR\tconfigKey\x12!\n" +
	"\fconfig_value\x18\x02 \x01(\tR\vconfigValue\"M\n" +
	"\x16GetConfigValueResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.configcenter.ConfigValueItemR\x05items2\xa1\x04\n" +
	"\x15ConfigCategoryService\x12V\n" +
	"\aGetList\x12$.configcenter.GetCategoryListRequest\x1a%.configcenter.GetCategoryListResponse\x12S\n" +
	"\x06GetAll\x12#.configcenter.GetCategoryAllRequest\x1a$.configcenter.GetCategoryAllResponse\x12\\\n" +
	"\tGetDetail\x12&.configcenter.GetCategoryDetailRequest\x1a'.configcenter.GetCategoryDetailResponse\x12S\n" +
	"\x06Create\x12#.configcenter.CreateCategoryRequest\x1a$.configcenter.CreateCategoryResponse\x12S\n" +
	"\x06Update\x12#.configcenter.UpdateCategoryRequest\x1a$.configcenter.UpdateCategoryResponse\x12S\n" +
	"\x06Delete\x12#.configcenter.DeleteCategoryRequest\x1a$.configcenter.DeleteCategoryResponse2\xae\x06\n" +
	"\x11ConfigItemService\x12R\n" +
	"\aGetList\x12\".configcenter.GetConfigListRequest\x1a#.configcenter.GetConfigListResponse\x12d\n" +
	"\rGetByCategory\x12(.configcenter.GetConfigByCategoryRequest\x1a).configcenter.GetConfigByCategoryResponse\x12X\n" +
	"\tGetDetail\x12$.configcenter.GetConfigDetailRequest\x1a%.configcenter.GetConfigDetailResponse\x12O\n" +
	"\x06Create\x12!.configcenter.CreateConfigRequest\x1a\".configcenter.CreateConfigResponse\x12O\n" +
	"\x06Update\x12!.configcenter.UpdateConfigRequest\x1a\".configcenter.UpdateConfigResponse\x12O\n" +
	"\x06Delete\x12!.configcenter.DeleteConfigRequest\x1a\".configcenter.DeleteConfigResponse\x12a\n" +
	"\fUpdateStatus\x12'.configcenter.UpdateConfigStatusRequest\x1a(.configcenter.UpdateConfigStatusResponse\x12X\n" +
	"\tSaveValue\x12$.configcenter.SaveConfigValueRequest\x1a%.configcenter.SaveConfigValueResponse\x12U\n" +
	"\bGetValue\x12#.configcenter.GetConfigValueRequest\x1a$.configcenter.GetConfigValueResponseB\x10Z\x0e./configcenterb\x06proto3"

var (
	file_configcenter_proto_rawDescOnce sync.Once
	file_configcenter_proto_rawDescData []byte
)

func file_configcenter_proto_rawDescGZIP() []byte {
	file_configcenter_proto_rawDescOnce.Do(func() {
		file_configcenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configcenter_proto_rawDesc), len(file_configcenter_proto_rawDesc)))
	})
	return file_configcenter_proto_rawDescData
}

var file_configcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_configcenter_proto_goTypes = []any{
	(*ConfigCategoryData)(nil),          // 0: configcenter.ConfigCategoryData
	(*GetCategoryListRequest)(nil),      // 1: configcenter.GetCategoryListRequest
	(*GetCategoryListResponse)(nil),     // 2: configcenter.GetCategoryListResponse
	(*GetCategoryAllRequest)(nil),       // 3: configcenter.GetCategoryAllRequest
	(*GetCategoryAllResponse)(nil),      // 4: configcenter.GetCategoryAllResponse
	(*GetCategoryDetailRequest)(nil),    // 5: configcenter.GetCategoryDetailRequest
	(*GetCategoryDetailResponse)(nil),   // 6: configcenter.GetCategoryDetailResponse
	(*CreateCategoryRequest)(nil),       // 7: configcenter.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),      // 8: configcenter.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),       // 9: configcenter.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),      // 10: configcenter.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),       // 11: configcenter.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),      // 12: configcenter.DeleteCategoryResponse
	(*ConfigOptionItem)(nil),            // 13: configcenter.ConfigOptionItem
	(*ConfigItemData)(nil),              // 14: configcenter.ConfigItemData
	(*GetConfigListRequest)(nil),        // 15: configcenter.GetConfigListRequest
	(*GetConfigListResponse)(nil),       // 16: configcenter.GetConfigListResponse
	(*GetConfigByCategoryRequest)(nil),  // 17: configcenter.GetConfigByCategoryRequest
	(*GetConfigByCategoryResponse)(nil), // 18: configcenter.GetConfigByCategoryResponse
	(*GetConfigDetailRequest)(nil),      // 19: configcenter.GetConfigDetailRequest
	(*GetConfigDetailResponse)(nil),     // 20: configcenter.GetConfigDetailResponse
	(*CreateConfigRequest)(nil),         // 21: configcenter.CreateConfigRequest
	(*CreateConfigResponse)(nil),        // 22: configcenter.CreateConfigResponse
	(*UpdateConfigRequest)(nil),         // 23: configcenter.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),        // 24: configcenter.UpdateConfigResponse
	(*DeleteConfigRequest)(nil),         // 25: configcenter.DeleteConfigRequest
	(*DeleteConfigResponse)(nil),        // 26: configcenter.DeleteConfigResponse
	(*UpdateConfigStatusRequest)(nil),   // 27: configcenter.UpdateConfigStatusRequest
	(*UpdateConfigStatusResponse)(nil),  // 28: configcenter.UpdateConfigStatusResponse
	(*SaveConfigValueRequest)(nil),      // 29: configcenter.SaveConfigValueRequest
	(*SaveConfigValueResponse)(nil),     // 30: configcenter.SaveConfigValueResponse
	(*GetConfigValueRequest)(nil),       // 31: configcenter.GetConfigValueRequest
	(*ConfigValueItem)(nil),             // 32: configcenter.ConfigValueItem
	(*GetConfigValueResponse)(nil),      // 33: configcenter.GetConfigValueResponse
	nil,                                 // 34: configcenter.SaveConfigValueRequest.ConfigValuesEntry
}
var file_configcenter_proto_depIdxs = []int32{
	0,  // 0: configcenter.GetCategoryListResponse.items:type_name -> configcenter.ConfigCategoryData
	0,  // 1: configcenter.GetCategoryAllResponse.items:type_name -> configcenter.ConfigCategoryData
	0,  // 2: configcenter.GetCategoryDetailResponse.data:type_name -> configcenter.ConfigCategoryData
	13, // 3: configcenter.ConfigItemData.options:type_name -> configcenter.ConfigOptionItem
	14, // 4: configcenter.GetConfigListResponse.items:type_name -> configcenter.ConfigItemData
	14, // 5: configcenter.GetConfigByCategoryResponse.items:type_name -> configcenter.ConfigItemData
	14, // 6: configcenter.GetConfigDetailResponse.data:type_name -> configcenter.ConfigItemData
	34, // 7: configcenter.SaveConfigValueRequest.config_values:type_name -> configcenter.SaveConfigValueRequest.ConfigValuesEntry
	32, // 8: configcenter.GetConfigValueResponse.items:type_name -> configcenter.ConfigValueItem
	1,  // 9: configcenter.ConfigCategoryService.GetList:input_type -> configcenter.GetCategoryListRequest
	3,  // 10: configcenter.ConfigCategoryService.GetAll:input_type -> configcenter.GetCategoryAllRequest
	5,  // 11: configcenter.ConfigCategoryService.GetDetail:input_type -> configcenter.GetCategoryDetailRequest
	7,  // 12: configcenter.ConfigCategoryService.Create:input_type -> configcenter.CreateCategoryRequest
	9,  // 13: configcenter.ConfigCategoryService.Update:input_type -> configcenter.UpdateCategoryRequest
	11, // 14: configcenter.ConfigCategoryService.Delete:input_type -> configcenter.DeleteCategoryRequest
	15, // 15: configcenter.ConfigItemService.GetList:input_type -> configcenter.GetConfigListRequest
	17, // 16: configcenter.ConfigItemService.GetByCategory:input_type -> configcenter.GetConfigByCategoryRequest
	19, // 17: configcenter.ConfigItemService.GetDetail:input_type -> configcenter.GetConfigDetailRequest
	21, // 18: configcenter.ConfigItemService.Create:input_type -> configcenter.CreateConfigRequest
	23, // 19: configcenter.ConfigItemService.Update:input_type -> configcenter.UpdateConfigRequest
	25, // 20: configcenter.ConfigItemService.Delete:input_type -> configcenter.DeleteConfigRequest
	27, // 21: configcenter.ConfigItemService.UpdateStatus:input_type -> configcenter.UpdateConfigStatusRequest
	29, // 22: configcenter.ConfigItemService.SaveValue:input_type -> configcenter.SaveConfigValueRequest
	31, // 23: configcenter.ConfigItemService.GetValue:input_type -> configcenter.GetConfigValueRequest
	2,  // 24: configcenter.ConfigCategoryService.GetList:output_type -> configcenter.GetCategoryListResponse
	4,  // 25: configcenter.ConfigCategoryService.GetAll:output_type -> configcenter.GetCategoryAllResponse
	6,  // 26: configcenter.ConfigCategoryService.GetDetail:output_type -> configcenter.GetCategoryDetailResponse
	8,  // 27: configcenter.ConfigCategoryService.Create:output_type -> configcenter.CreateCategoryResponse
	10, // 28: configcenter.ConfigCategoryService.Update:output_type -> configcenter.UpdateCategoryResponse
	12, // 29: configcenter.ConfigCategoryService.Delete:output_type -> configcenter.DeleteCategoryResponse
	16, // 30: configcenter.ConfigItemService.GetList:output_type -> configcenter.GetConfigListResponse
	18, // 31: configcenter.ConfigItemService.GetByCategory:output_type -> configcenter.GetConfigByCategoryResponse
	20, // 32: configcenter.ConfigItemService.GetDetail:output_type -> configcenter.GetConfigDetailResponse
	22, // 33: configcenter.ConfigItemService.Create:output_type -> configcenter.CreateConfigResponse
	24, // 34: configcenter.ConfigItemService.Update:output_type -> configcenter.UpdateConfigResponse
	26, // 35: configcenter.ConfigItemService.Delete:output_type -> configcenter.DeleteConfigResponse
	28, // 36: configcenter.ConfigItemService.UpdateStatus:output_type -> configcenter.UpdateConfigStatusResponse
	30, // 37: configcenter.ConfigItemService.SaveValue:output_type -> configcenter.SaveConfigValueResponse
	33, // 38: configcenter.ConfigItemService.GetValue:output_type -> configcenter.GetConfigValueResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_configcenter_proto_init() }
func file_configcenter_proto_init() {
	if File_configcenter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configcenter_proto_rawDesc), len(file_configcenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_configcenter_proto_goTypes,
		DependencyIndexes: file_configcenter_proto_depIdxs,
		MessageInfos:      file_configcenter_proto_msgTypes,
	}.Build()
	File_configcenter_proto = out.File
	file_configcenter_proto_goTypes = nil
	file_configcenter_proto_depIdxs = nil
}
