// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.11
// source: configcenter.proto

package configcenter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigCategoryService_GetList_FullMethodName   = "/configcenter.ConfigCategoryService/GetList"
	ConfigCategoryService_GetAll_FullMethodName    = "/configcenter.ConfigCategoryService/GetAll"
	ConfigCategoryService_GetDetail_FullMethodName = "/configcenter.ConfigCategoryService/GetDetail"
	ConfigCategoryService_Create_FullMethodName    = "/configcenter.ConfigCategoryService/Create"
	ConfigCategoryService_Update_FullMethodName    = "/configcenter.ConfigCategoryService/Update"
	ConfigCategoryService_Delete_FullMethodName    = "/configcenter.ConfigCategoryService/Delete"
)

// ConfigCategoryServiceClient is the client API for ConfigCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigCategoryServiceClient interface {
	GetList(ctx context.Context, in *GetCategoryListRequest, opts ...grpc.CallOption) (*GetCategoryListResponse, error)
	GetAll(ctx context.Context, in *GetCategoryAllRequest, opts ...grpc.CallOption) (*GetCategoryAllResponse, error)
	GetDetail(ctx context.Context, in *GetCategoryDetailRequest, opts ...grpc.CallOption) (*GetCategoryDetailResponse, error)
	Create(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error)
	Update(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error)
	Delete(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
}

type configCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigCategoryServiceClient(cc grpc.ClientConnInterface) ConfigCategoryServiceClient {
	return &configCategoryServiceClient{cc}
}

func (c *configCategoryServiceClient) GetList(ctx context.Context, in *GetCategoryListRequest, opts ...grpc.CallOption) (*GetCategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryListResponse)
	err := c.cc.Invoke(ctx, ConfigCategoryService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCategoryServiceClient) GetAll(ctx context.Context, in *GetCategoryAllRequest, opts ...grpc.CallOption) (*GetCategoryAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryAllResponse)
	err := c.cc.Invoke(ctx, ConfigCategoryService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCategoryServiceClient) GetDetail(ctx context.Context, in *GetCategoryDetailRequest, opts ...grpc.CallOption) (*GetCategoryDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryDetailResponse)
	err := c.cc.Invoke(ctx, ConfigCategoryService_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCategoryServiceClient) Create(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*CreateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCategoryResponse)
	err := c.cc.Invoke(ctx, ConfigCategoryService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCategoryServiceClient) Update(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*UpdateCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCategoryResponse)
	err := c.cc.Invoke(ctx, ConfigCategoryService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configCategoryServiceClient) Delete(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, ConfigCategoryService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigCategoryServiceServer is the server API for ConfigCategoryService service.
// All implementations must embed UnimplementedConfigCategoryServiceServer
// for forward compatibility.
type ConfigCategoryServiceServer interface {
	GetList(context.Context, *GetCategoryListRequest) (*GetCategoryListResponse, error)
	GetAll(context.Context, *GetCategoryAllRequest) (*GetCategoryAllResponse, error)
	GetDetail(context.Context, *GetCategoryDetailRequest) (*GetCategoryDetailResponse, error)
	Create(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error)
	Update(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error)
	Delete(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	mustEmbedUnimplementedConfigCategoryServiceServer()
}

// UnimplementedConfigCategoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigCategoryServiceServer struct{}

func (UnimplementedConfigCategoryServiceServer) GetList(context.Context, *GetCategoryListRequest) (*GetCategoryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedConfigCategoryServiceServer) GetAll(context.Context, *GetCategoryAllRequest) (*GetCategoryAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedConfigCategoryServiceServer) GetDetail(context.Context, *GetCategoryDetailRequest) (*GetCategoryDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedConfigCategoryServiceServer) Create(context.Context, *CreateCategoryRequest) (*CreateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedConfigCategoryServiceServer) Update(context.Context, *UpdateCategoryRequest) (*UpdateCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedConfigCategoryServiceServer) Delete(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConfigCategoryServiceServer) mustEmbedUnimplementedConfigCategoryServiceServer() {}
func (UnimplementedConfigCategoryServiceServer) testEmbeddedByValue()                               {}

// UnsafeConfigCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigCategoryServiceServer will
// result in compilation errors.
type UnsafeConfigCategoryServiceServer interface {
	mustEmbedUnimplementedConfigCategoryServiceServer()
}

func RegisterConfigCategoryServiceServer(s grpc.ServiceRegistrar, srv ConfigCategoryServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigCategoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigCategoryService_ServiceDesc, srv)
}

func _ConfigCategoryService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCategoryServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCategoryService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCategoryServiceServer).GetList(ctx, req.(*GetCategoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCategoryService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCategoryServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCategoryService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCategoryServiceServer).GetAll(ctx, req.(*GetCategoryAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCategoryService_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCategoryServiceServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCategoryService_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCategoryServiceServer).GetDetail(ctx, req.(*GetCategoryDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCategoryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCategoryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCategoryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCategoryServiceServer).Create(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCategoryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCategoryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCategoryService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCategoryServiceServer).Update(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigCategoryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigCategoryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigCategoryService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigCategoryServiceServer).Delete(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigCategoryService_ServiceDesc is the grpc.ServiceDesc for ConfigCategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigCategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configcenter.ConfigCategoryService",
	HandlerType: (*ConfigCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _ConfigCategoryService_GetList_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ConfigCategoryService_GetAll_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _ConfigCategoryService_GetDetail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ConfigCategoryService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ConfigCategoryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConfigCategoryService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configcenter.proto",
}

const (
	ConfigItemService_GetList_FullMethodName       = "/configcenter.ConfigItemService/GetList"
	ConfigItemService_GetByCategory_FullMethodName = "/configcenter.ConfigItemService/GetByCategory"
	ConfigItemService_GetDetail_FullMethodName     = "/configcenter.ConfigItemService/GetDetail"
	ConfigItemService_Create_FullMethodName        = "/configcenter.ConfigItemService/Create"
	ConfigItemService_Update_FullMethodName        = "/configcenter.ConfigItemService/Update"
	ConfigItemService_Delete_FullMethodName        = "/configcenter.ConfigItemService/Delete"
	ConfigItemService_UpdateStatus_FullMethodName  = "/configcenter.ConfigItemService/UpdateStatus"
	ConfigItemService_SaveValue_FullMethodName     = "/configcenter.ConfigItemService/SaveValue"
	ConfigItemService_GetValue_FullMethodName      = "/configcenter.ConfigItemService/GetValue"
)

// ConfigItemServiceClient is the client API for ConfigItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigItemServiceClient interface {
	GetList(ctx context.Context, in *GetConfigListRequest, opts ...grpc.CallOption) (*GetConfigListResponse, error)
	GetByCategory(ctx context.Context, in *GetConfigByCategoryRequest, opts ...grpc.CallOption) (*GetConfigByCategoryResponse, error)
	GetDetail(ctx context.Context, in *GetConfigDetailRequest, opts ...grpc.CallOption) (*GetConfigDetailResponse, error)
	Create(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error)
	Update(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	Delete(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateConfigStatusRequest, opts ...grpc.CallOption) (*UpdateConfigStatusResponse, error)
	SaveValue(ctx context.Context, in *SaveConfigValueRequest, opts ...grpc.CallOption) (*SaveConfigValueResponse, error)
	GetValue(ctx context.Context, in *GetConfigValueRequest, opts ...grpc.CallOption) (*GetConfigValueResponse, error)
}

type configItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigItemServiceClient(cc grpc.ClientConnInterface) ConfigItemServiceClient {
	return &configItemServiceClient{cc}
}

func (c *configItemServiceClient) GetList(ctx context.Context, in *GetConfigListRequest, opts ...grpc.CallOption) (*GetConfigListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigListResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) GetByCategory(ctx context.Context, in *GetConfigByCategoryRequest, opts ...grpc.CallOption) (*GetConfigByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigByCategoryResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_GetByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) GetDetail(ctx context.Context, in *GetConfigDetailRequest, opts ...grpc.CallOption) (*GetConfigDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigDetailResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) Create(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConfigResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) Update(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) Delete(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConfigResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) UpdateStatus(ctx context.Context, in *UpdateConfigStatusRequest, opts ...grpc.CallOption) (*UpdateConfigStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigStatusResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) SaveValue(ctx context.Context, in *SaveConfigValueRequest, opts ...grpc.CallOption) (*SaveConfigValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveConfigValueResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_SaveValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configItemServiceClient) GetValue(ctx context.Context, in *GetConfigValueRequest, opts ...grpc.CallOption) (*GetConfigValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigValueResponse)
	err := c.cc.Invoke(ctx, ConfigItemService_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigItemServiceServer is the server API for ConfigItemService service.
// All implementations must embed UnimplementedConfigItemServiceServer
// for forward compatibility.
type ConfigItemServiceServer interface {
	GetList(context.Context, *GetConfigListRequest) (*GetConfigListResponse, error)
	GetByCategory(context.Context, *GetConfigByCategoryRequest) (*GetConfigByCategoryResponse, error)
	GetDetail(context.Context, *GetConfigDetailRequest) (*GetConfigDetailResponse, error)
	Create(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error)
	Update(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	Delete(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error)
	UpdateStatus(context.Context, *UpdateConfigStatusRequest) (*UpdateConfigStatusResponse, error)
	SaveValue(context.Context, *SaveConfigValueRequest) (*SaveConfigValueResponse, error)
	GetValue(context.Context, *GetConfigValueRequest) (*GetConfigValueResponse, error)
	mustEmbedUnimplementedConfigItemServiceServer()
}

// UnimplementedConfigItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigItemServiceServer struct{}

func (UnimplementedConfigItemServiceServer) GetList(context.Context, *GetConfigListRequest) (*GetConfigListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedConfigItemServiceServer) GetByCategory(context.Context, *GetConfigByCategoryRequest) (*GetConfigByCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByCategory not implemented")
}
func (UnimplementedConfigItemServiceServer) GetDetail(context.Context, *GetConfigDetailRequest) (*GetConfigDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedConfigItemServiceServer) Create(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedConfigItemServiceServer) Update(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedConfigItemServiceServer) Delete(context.Context, *DeleteConfigRequest) (*DeleteConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConfigItemServiceServer) UpdateStatus(context.Context, *UpdateConfigStatusRequest) (*UpdateConfigStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedConfigItemServiceServer) SaveValue(context.Context, *SaveConfigValueRequest) (*SaveConfigValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveValue not implemented")
}
func (UnimplementedConfigItemServiceServer) GetValue(context.Context, *GetConfigValueRequest) (*GetConfigValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedConfigItemServiceServer) mustEmbedUnimplementedConfigItemServiceServer() {}
func (UnimplementedConfigItemServiceServer) testEmbeddedByValue()                           {}

// UnsafeConfigItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigItemServiceServer will
// result in compilation errors.
type UnsafeConfigItemServiceServer interface {
	mustEmbedUnimplementedConfigItemServiceServer()
}

func RegisterConfigItemServiceServer(s grpc.ServiceRegistrar, srv ConfigItemServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigItemService_ServiceDesc, srv)
}

func _ConfigItemService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).GetList(ctx, req.(*GetConfigListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_GetByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).GetByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_GetByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).GetByCategory(ctx, req.(*GetConfigByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).GetDetail(ctx, req.(*GetConfigDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).Create(ctx, req.(*CreateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).Update(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).Delete(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).UpdateStatus(ctx, req.(*UpdateConfigStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_SaveValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).SaveValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_SaveValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).SaveValue(ctx, req.(*SaveConfigValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigItemService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigItemServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigItemService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigItemServiceServer).GetValue(ctx, req.(*GetConfigValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigItemService_ServiceDesc is the grpc.ServiceDesc for ConfigItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configcenter.ConfigItemService",
	HandlerType: (*ConfigItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _ConfigItemService_GetList_Handler,
		},
		{
			MethodName: "GetByCategory",
			Handler:    _ConfigItemService_GetByCategory_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _ConfigItemService_GetDetail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ConfigItemService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ConfigItemService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConfigItemService_Delete_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _ConfigItemService_UpdateStatus_Handler,
		},
		{
			MethodName: "SaveValue",
			Handler:    _ConfigItemService_SaveValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _ConfigItemService_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configcenter.proto",
}
