// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package server

import (
	"context"

	"common/common"
	"common/internal/logic/commonservice"
	"common/internal/svc"
)

type CommonServiceServer struct {
	svcCtx *svc.ServiceContext
	common.UnimplementedCommonServiceServer
}

func NewCommonServiceServer(svcCtx *svc.ServiceContext) *CommonServiceServer {
	return &CommonServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonServiceServer) GetCaptcha(ctx context.Context, in *common.GetCaptchaRequest) (*common.GetCaptchaResponse, error) {
	l := commonservicelogic.NewGetCaptchaLogic(ctx, s.svcCtx)
	return l.GetCaptcha(in)
}

func (s *CommonServiceServer) GetMenu(ctx context.Context, in *common.GetMenuRequest) (*common.GetMenuResponse, error) {
	l := commonservicelogic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}
