// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: configcenter.proto

package server

import (
	"context"

	"configcenter/configcenter"
	"configcenter/internal/logic/configcategoryservice"
	"configcenter/internal/svc"
)

type ConfigCategoryServiceServer struct {
	svcCtx *svc.ServiceContext
	configcenter.UnimplementedConfigCategoryServiceServer
}

func NewConfigCategoryServiceServer(svcCtx *svc.ServiceContext) *ConfigCategoryServiceServer {
	return &ConfigCategoryServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ConfigCategoryServiceServer) GetList(ctx context.Context, in *configcenter.GetCategoryListRequest) (*configcenter.GetCategoryListResponse, error) {
	l := configcategoryservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *ConfigCategoryServiceServer) GetAll(ctx context.Context, in *configcenter.GetCategoryAllRequest) (*configcenter.GetCategoryAllResponse, error) {
	l := configcategoryservicelogic.NewGetAllLogic(ctx, s.svcCtx)
	return l.GetAll(in)
}

func (s *ConfigCategoryServiceServer) GetDetail(ctx context.Context, in *configcenter.GetCategoryDetailRequest) (*configcenter.GetCategoryDetailResponse, error) {
	l := configcategoryservicelogic.NewGetDetailLogic(ctx, s.svcCtx)
	return l.GetDetail(in)
}

func (s *ConfigCategoryServiceServer) Create(ctx context.Context, in *configcenter.CreateCategoryRequest) (*configcenter.CreateCategoryResponse, error) {
	l := configcategoryservicelogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *ConfigCategoryServiceServer) Update(ctx context.Context, in *configcenter.UpdateCategoryRequest) (*configcenter.UpdateCategoryResponse, error) {
	l := configcategoryservicelogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *ConfigCategoryServiceServer) Delete(ctx context.Context, in *configcenter.DeleteCategoryRequest) (*configcenter.DeleteCategoryResponse, error) {
	l := configcategoryservicelogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
