// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package authservice

import (
	"context"

	"auth/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckTokenRequest    = auth.CheckTokenRequest
	CheckTokenResponse   = auth.CheckTokenResponse
	RefreshTokenRequest  = auth.RefreshTokenRequest
	RefreshTokenResponse = auth.RefreshTokenResponse

	AuthService interface {
		CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	client := auth.NewAuthServiceClient(m.cli.Conn())
	return client.CheckToken(ctx, in, opts...)
}

func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	client := auth.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}
