// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: configcenter.proto

package configitemservice

import (
	"context"

	"configcenter/configcenter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConfigCategoryData          = configcenter.ConfigCategoryData
	ConfigItemData              = configcenter.ConfigItemData
	ConfigOptionItem            = configcenter.ConfigOptionItem
	ConfigValueItem             = configcenter.ConfigValueItem
	CreateCategoryRequest       = configcenter.CreateCategoryRequest
	CreateCategoryResponse      = configcenter.CreateCategoryResponse
	CreateConfigRequest         = configcenter.CreateConfigRequest
	CreateConfigResponse        = configcenter.CreateConfigResponse
	DeleteCategoryRequest       = configcenter.DeleteCategoryRequest
	DeleteCategoryResponse      = configcenter.DeleteCategoryResponse
	DeleteConfigRequest         = configcenter.DeleteConfigRequest
	DeleteConfigResponse        = configcenter.DeleteConfigResponse
	GetCategoryAllRequest       = configcenter.GetCategoryAllRequest
	GetCategoryAllResponse      = configcenter.GetCategoryAllResponse
	GetCategoryDetailRequest    = configcenter.GetCategoryDetailRequest
	GetCategoryDetailResponse   = configcenter.GetCategoryDetailResponse
	GetCategoryListRequest      = configcenter.GetCategoryListRequest
	GetCategoryListResponse     = configcenter.GetCategoryListResponse
	GetConfigByCategoryRequest  = configcenter.GetConfigByCategoryRequest
	GetConfigByCategoryResponse = configcenter.GetConfigByCategoryResponse
	GetConfigDetailRequest      = configcenter.GetConfigDetailRequest
	GetConfigDetailResponse     = configcenter.GetConfigDetailResponse
	GetConfigListRequest        = configcenter.GetConfigListRequest
	GetConfigListResponse       = configcenter.GetConfigListResponse
	GetConfigValueRequest       = configcenter.GetConfigValueRequest
	GetConfigValueResponse      = configcenter.GetConfigValueResponse
	SaveConfigValueRequest      = configcenter.SaveConfigValueRequest
	SaveConfigValueResponse     = configcenter.SaveConfigValueResponse
	UpdateCategoryRequest       = configcenter.UpdateCategoryRequest
	UpdateCategoryResponse      = configcenter.UpdateCategoryResponse
	UpdateConfigRequest         = configcenter.UpdateConfigRequest
	UpdateConfigResponse        = configcenter.UpdateConfigResponse
	UpdateConfigStatusRequest   = configcenter.UpdateConfigStatusRequest
	UpdateConfigStatusResponse  = configcenter.UpdateConfigStatusResponse

	ConfigItemService interface {
		GetList(ctx context.Context, in *GetConfigListRequest, opts ...grpc.CallOption) (*GetConfigListResponse, error)
		GetByCategory(ctx context.Context, in *GetConfigByCategoryRequest, opts ...grpc.CallOption) (*GetConfigByCategoryResponse, error)
		GetDetail(ctx context.Context, in *GetConfigDetailRequest, opts ...grpc.CallOption) (*GetConfigDetailResponse, error)
		Create(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error)
		Update(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
		Delete(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error)
		UpdateStatus(ctx context.Context, in *UpdateConfigStatusRequest, opts ...grpc.CallOption) (*UpdateConfigStatusResponse, error)
		SaveValue(ctx context.Context, in *SaveConfigValueRequest, opts ...grpc.CallOption) (*SaveConfigValueResponse, error)
		GetValue(ctx context.Context, in *GetConfigValueRequest, opts ...grpc.CallOption) (*GetConfigValueResponse, error)
	}

	defaultConfigItemService struct {
		cli zrpc.Client
	}
)

func NewConfigItemService(cli zrpc.Client) ConfigItemService {
	return &defaultConfigItemService{
		cli: cli,
	}
}

func (m *defaultConfigItemService) GetList(ctx context.Context, in *GetConfigListRequest, opts ...grpc.CallOption) (*GetConfigListResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultConfigItemService) GetByCategory(ctx context.Context, in *GetConfigByCategoryRequest, opts ...grpc.CallOption) (*GetConfigByCategoryResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.GetByCategory(ctx, in, opts...)
}

func (m *defaultConfigItemService) GetDetail(ctx context.Context, in *GetConfigDetailRequest, opts ...grpc.CallOption) (*GetConfigDetailResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.GetDetail(ctx, in, opts...)
}

func (m *defaultConfigItemService) Create(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultConfigItemService) Update(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

func (m *defaultConfigItemService) Delete(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*DeleteConfigResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}

func (m *defaultConfigItemService) UpdateStatus(ctx context.Context, in *UpdateConfigStatusRequest, opts ...grpc.CallOption) (*UpdateConfigStatusResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.UpdateStatus(ctx, in, opts...)
}

func (m *defaultConfigItemService) SaveValue(ctx context.Context, in *SaveConfigValueRequest, opts ...grpc.CallOption) (*SaveConfigValueResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.SaveValue(ctx, in, opts...)
}

func (m *defaultConfigItemService) GetValue(ctx context.Context, in *GetConfigValueRequest, opts ...grpc.CallOption) (*GetConfigValueResponse, error) {
	client := configcenter.NewConfigItemServiceClient(m.cli.Conn())
	return client.GetValue(ctx, in, opts...)
}
