// 声明 proto 使用的语法版本

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.11
// source: system.proto

// proto 包名

package system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuleService_GetList_FullMethodName    = "/system.RuleService/GetList"
	RuleService_Save_FullMethodName       = "/system.RuleService/Save"
	RuleService_UpStatus_FullMethodName   = "/system.RuleService/UpStatus"
	RuleService_Del_FullMethodName        = "/system.RuleService/Del"
	RuleService_GetContent_FullMethodName = "/system.RuleService/GetContent"
	RuleService_GetParent_FullMethodName  = "/system.RuleService/GetParent"
	RuleService_GetRoutes_FullMethodName  = "/system.RuleService/GetRoutes"
)

// RuleServiceClient is the client API for RuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type RuleServiceClient interface {
	GetList(ctx context.Context, in *GetRuleListRequest, opts ...grpc.CallOption) (*GetRuleListResponse, error)
	Save(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error)
	UpStatus(ctx context.Context, in *UpStatusRuleRequest, opts ...grpc.CallOption) (*UpStatusRuleResponse, error)
	Del(ctx context.Context, in *DelRuleRequest, opts ...grpc.CallOption) (*DelRuleResponse, error)
	GetContent(ctx context.Context, in *GetRuleContentRequest, opts ...grpc.CallOption) (*GetRuleContentResponse, error)
	GetParent(ctx context.Context, in *GetRuleParentRequest, opts ...grpc.CallOption) (*GetRuleParentResponse, error)
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
}

type ruleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleServiceClient(cc grpc.ClientConnInterface) RuleServiceClient {
	return &ruleServiceClient{cc}
}

func (c *ruleServiceClient) GetList(ctx context.Context, in *GetRuleListRequest, opts ...grpc.CallOption) (*GetRuleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleListResponse)
	err := c.cc.Invoke(ctx, RuleService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) Save(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) UpStatus(ctx context.Context, in *UpStatusRuleRequest, opts ...grpc.CallOption) (*UpStatusRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpStatusRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_UpStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) Del(ctx context.Context, in *DelRuleRequest, opts ...grpc.CallOption) (*DelRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelRuleResponse)
	err := c.cc.Invoke(ctx, RuleService_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetContent(ctx context.Context, in *GetRuleContentRequest, opts ...grpc.CallOption) (*GetRuleContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleContentResponse)
	err := c.cc.Invoke(ctx, RuleService_GetContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetParent(ctx context.Context, in *GetRuleParentRequest, opts ...grpc.CallOption) (*GetRuleParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleParentResponse)
	err := c.cc.Invoke(ctx, RuleService_GetParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleServiceClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, RuleService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServiceServer is the server API for RuleService service.
// All implementations must embed UnimplementedRuleServiceServer
// for forward compatibility.
//
// 定义服务
type RuleServiceServer interface {
	GetList(context.Context, *GetRuleListRequest) (*GetRuleListResponse, error)
	Save(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error)
	UpStatus(context.Context, *UpStatusRuleRequest) (*UpStatusRuleResponse, error)
	Del(context.Context, *DelRuleRequest) (*DelRuleResponse, error)
	GetContent(context.Context, *GetRuleContentRequest) (*GetRuleContentResponse, error)
	GetParent(context.Context, *GetRuleParentRequest) (*GetRuleParentResponse, error)
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	mustEmbedUnimplementedRuleServiceServer()
}

// UnimplementedRuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuleServiceServer struct{}

func (UnimplementedRuleServiceServer) GetList(context.Context, *GetRuleListRequest) (*GetRuleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedRuleServiceServer) Save(context.Context, *SaveRuleRequest) (*SaveRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedRuleServiceServer) UpStatus(context.Context, *UpStatusRuleRequest) (*UpStatusRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpStatus not implemented")
}
func (UnimplementedRuleServiceServer) Del(context.Context, *DelRuleRequest) (*DelRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedRuleServiceServer) GetContent(context.Context, *GetRuleContentRequest) (*GetRuleContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedRuleServiceServer) GetParent(context.Context, *GetRuleParentRequest) (*GetRuleParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParent not implemented")
}
func (UnimplementedRuleServiceServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedRuleServiceServer) mustEmbedUnimplementedRuleServiceServer() {}
func (UnimplementedRuleServiceServer) testEmbeddedByValue()                     {}

// UnsafeRuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleServiceServer will
// result in compilation errors.
type UnsafeRuleServiceServer interface {
	mustEmbedUnimplementedRuleServiceServer()
}

func RegisterRuleServiceServer(s grpc.ServiceRegistrar, srv RuleServiceServer) {
	// If the following call panics, it indicates UnimplementedRuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuleService_ServiceDesc, srv)
}

func _RuleService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetList(ctx, req.(*GetRuleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).Save(ctx, req.(*SaveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_UpStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpStatusRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).UpStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_UpStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).UpStatus(ctx, req.(*UpStatusRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).Del(ctx, req.(*DelRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetContent(ctx, req.(*GetRuleContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_GetParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetParent(ctx, req.(*GetRuleParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServiceServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleService_ServiceDesc is the grpc.ServiceDesc for RuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.RuleService",
	HandlerType: (*RuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _RuleService_GetList_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _RuleService_Save_Handler,
		},
		{
			MethodName: "UpStatus",
			Handler:    _RuleService_UpStatus_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _RuleService_Del_Handler,
		},
		{
			MethodName: "GetContent",
			Handler:    _RuleService_GetContent_Handler,
		},
		{
			MethodName: "GetParent",
			Handler:    _RuleService_GetParent_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _RuleService_GetRoutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}

const (
	DeptService_GetList_FullMethodName   = "/system.DeptService/GetList"
	DeptService_Save_FullMethodName      = "/system.DeptService/Save"
	DeptService_UpState_FullMethodName   = "/system.DeptService/UpState"
	DeptService_Del_FullMethodName       = "/system.DeptService/Del"
	DeptService_GetParent_FullMethodName = "/system.DeptService/GetParent"
)

// DeptServiceClient is the client API for DeptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type DeptServiceClient interface {
	GetList(ctx context.Context, in *GetDeptListRequest, opts ...grpc.CallOption) (*GetDeptListResponse, error)
	Save(ctx context.Context, in *SaveDeptRequest, opts ...grpc.CallOption) (*SaveDeptResponse, error)
	UpState(ctx context.Context, in *UpStatusDeptRequest, opts ...grpc.CallOption) (*UpStatusDeptResponse, error)
	Del(ctx context.Context, in *DelDeptRequest, opts ...grpc.CallOption) (*DelDeptResponse, error)
	GetParent(ctx context.Context, in *GetDeptParentRequest, opts ...grpc.CallOption) (*GetDeptParentResponse, error)
}

type deptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeptServiceClient(cc grpc.ClientConnInterface) DeptServiceClient {
	return &deptServiceClient{cc}
}

func (c *deptServiceClient) GetList(ctx context.Context, in *GetDeptListRequest, opts ...grpc.CallOption) (*GetDeptListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeptListResponse)
	err := c.cc.Invoke(ctx, DeptService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptServiceClient) Save(ctx context.Context, in *SaveDeptRequest, opts ...grpc.CallOption) (*SaveDeptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDeptResponse)
	err := c.cc.Invoke(ctx, DeptService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptServiceClient) UpState(ctx context.Context, in *UpStatusDeptRequest, opts ...grpc.CallOption) (*UpStatusDeptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpStatusDeptResponse)
	err := c.cc.Invoke(ctx, DeptService_UpState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptServiceClient) Del(ctx context.Context, in *DelDeptRequest, opts ...grpc.CallOption) (*DelDeptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelDeptResponse)
	err := c.cc.Invoke(ctx, DeptService_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptServiceClient) GetParent(ctx context.Context, in *GetDeptParentRequest, opts ...grpc.CallOption) (*GetDeptParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeptParentResponse)
	err := c.cc.Invoke(ctx, DeptService_GetParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeptServiceServer is the server API for DeptService service.
// All implementations must embed UnimplementedDeptServiceServer
// for forward compatibility.
//
// 定义服务
type DeptServiceServer interface {
	GetList(context.Context, *GetDeptListRequest) (*GetDeptListResponse, error)
	Save(context.Context, *SaveDeptRequest) (*SaveDeptResponse, error)
	UpState(context.Context, *UpStatusDeptRequest) (*UpStatusDeptResponse, error)
	Del(context.Context, *DelDeptRequest) (*DelDeptResponse, error)
	GetParent(context.Context, *GetDeptParentRequest) (*GetDeptParentResponse, error)
	mustEmbedUnimplementedDeptServiceServer()
}

// UnimplementedDeptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeptServiceServer struct{}

func (UnimplementedDeptServiceServer) GetList(context.Context, *GetDeptListRequest) (*GetDeptListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedDeptServiceServer) Save(context.Context, *SaveDeptRequest) (*SaveDeptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedDeptServiceServer) UpState(context.Context, *UpStatusDeptRequest) (*UpStatusDeptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpState not implemented")
}
func (UnimplementedDeptServiceServer) Del(context.Context, *DelDeptRequest) (*DelDeptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedDeptServiceServer) GetParent(context.Context, *GetDeptParentRequest) (*GetDeptParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParent not implemented")
}
func (UnimplementedDeptServiceServer) mustEmbedUnimplementedDeptServiceServer() {}
func (UnimplementedDeptServiceServer) testEmbeddedByValue()                     {}

// UnsafeDeptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeptServiceServer will
// result in compilation errors.
type UnsafeDeptServiceServer interface {
	mustEmbedUnimplementedDeptServiceServer()
}

func RegisterDeptServiceServer(s grpc.ServiceRegistrar, srv DeptServiceServer) {
	// If the following call panics, it indicates UnimplementedDeptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeptService_ServiceDesc, srv)
}

func _DeptService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeptListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeptService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServiceServer).GetList(ctx, req.(*GetDeptListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeptService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDeptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeptService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServiceServer).Save(ctx, req.(*SaveDeptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeptService_UpState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpStatusDeptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServiceServer).UpState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeptService_UpState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServiceServer).UpState(ctx, req.(*UpStatusDeptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeptService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelDeptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeptService_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServiceServer).Del(ctx, req.(*DelDeptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeptService_GetParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeptParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServiceServer).GetParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeptService_GetParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServiceServer).GetParent(ctx, req.(*GetDeptParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeptService_ServiceDesc is the grpc.ServiceDesc for DeptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.DeptService",
	HandlerType: (*DeptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _DeptService_GetList_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _DeptService_Save_Handler,
		},
		{
			MethodName: "UpState",
			Handler:    _DeptService_UpState_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _DeptService_Del_Handler,
		},
		{
			MethodName: "GetParent",
			Handler:    _DeptService_GetParent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}

const (
	RoleService_GetList_FullMethodName     = "/system.RoleService/GetList"
	RoleService_Save_FullMethodName        = "/system.RoleService/Save"
	RoleService_UpStatus_FullMethodName    = "/system.RoleService/UpStatus"
	RoleService_Del_FullMethodName         = "/system.RoleService/Del"
	RoleService_GetParent_FullMethodName   = "/system.RoleService/GetParent"
	RoleService_GetMenuList_FullMethodName = "/system.RoleService/GetMenuList"
)

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type RoleServiceClient interface {
	GetList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error)
	Save(ctx context.Context, in *SaveRoleRequest, opts ...grpc.CallOption) (*SaveRoleResponse, error)
	UpStatus(ctx context.Context, in *UpStatusRoleRequest, opts ...grpc.CallOption) (*UpStatusRoleResponse, error)
	Del(ctx context.Context, in *DelRoleRequest, opts ...grpc.CallOption) (*DelRoleResponse, error)
	GetParent(ctx context.Context, in *GetRoleParentRequest, opts ...grpc.CallOption) (*GetRoleParentResponse, error)
	GetMenuList(ctx context.Context, in *GetMenuListRequest, opts ...grpc.CallOption) (*GetMenuListResponse, error)
}

type roleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleServiceClient(cc grpc.ClientConnInterface) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) GetList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleListResponse)
	err := c.cc.Invoke(ctx, RoleService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) Save(ctx context.Context, in *SaveRoleRequest, opts ...grpc.CallOption) (*SaveRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveRoleResponse)
	err := c.cc.Invoke(ctx, RoleService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) UpStatus(ctx context.Context, in *UpStatusRoleRequest, opts ...grpc.CallOption) (*UpStatusRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpStatusRoleResponse)
	err := c.cc.Invoke(ctx, RoleService_UpStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) Del(ctx context.Context, in *DelRoleRequest, opts ...grpc.CallOption) (*DelRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelRoleResponse)
	err := c.cc.Invoke(ctx, RoleService_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetParent(ctx context.Context, in *GetRoleParentRequest, opts ...grpc.CallOption) (*GetRoleParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleParentResponse)
	err := c.cc.Invoke(ctx, RoleService_GetParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) GetMenuList(ctx context.Context, in *GetMenuListRequest, opts ...grpc.CallOption) (*GetMenuListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuListResponse)
	err := c.cc.Invoke(ctx, RoleService_GetMenuList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
// All implementations must embed UnimplementedRoleServiceServer
// for forward compatibility.
//
// 定义服务
type RoleServiceServer interface {
	GetList(context.Context, *GetRoleListRequest) (*GetRoleListResponse, error)
	Save(context.Context, *SaveRoleRequest) (*SaveRoleResponse, error)
	UpStatus(context.Context, *UpStatusRoleRequest) (*UpStatusRoleResponse, error)
	Del(context.Context, *DelRoleRequest) (*DelRoleResponse, error)
	GetParent(context.Context, *GetRoleParentRequest) (*GetRoleParentResponse, error)
	GetMenuList(context.Context, *GetMenuListRequest) (*GetMenuListResponse, error)
	mustEmbedUnimplementedRoleServiceServer()
}

// UnimplementedRoleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleServiceServer struct{}

func (UnimplementedRoleServiceServer) GetList(context.Context, *GetRoleListRequest) (*GetRoleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedRoleServiceServer) Save(context.Context, *SaveRoleRequest) (*SaveRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedRoleServiceServer) UpStatus(context.Context, *UpStatusRoleRequest) (*UpStatusRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpStatus not implemented")
}
func (UnimplementedRoleServiceServer) Del(context.Context, *DelRoleRequest) (*DelRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedRoleServiceServer) GetParent(context.Context, *GetRoleParentRequest) (*GetRoleParentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParent not implemented")
}
func (UnimplementedRoleServiceServer) GetMenuList(context.Context, *GetMenuListRequest) (*GetMenuListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenuList not implemented")
}
func (UnimplementedRoleServiceServer) mustEmbedUnimplementedRoleServiceServer() {}
func (UnimplementedRoleServiceServer) testEmbeddedByValue()                     {}

// UnsafeRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServiceServer will
// result in compilation errors.
type UnsafeRoleServiceServer interface {
	mustEmbedUnimplementedRoleServiceServer()
}

func RegisterRoleServiceServer(s grpc.ServiceRegistrar, srv RoleServiceServer) {
	// If the following call panics, it indicates UnimplementedRoleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleService_ServiceDesc, srv)
}

func _RoleService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetList(ctx, req.(*GetRoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Save(ctx, req.(*SaveRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_UpStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpStatusRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).UpStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_UpStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).UpStatus(ctx, req.(*UpStatusRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).Del(ctx, req.(*DelRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_GetParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetParent(ctx, req.(*GetRoleParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_GetMenuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).GetMenuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_GetMenuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).GetMenuList(ctx, req.(*GetMenuListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleService_ServiceDesc is the grpc.ServiceDesc for RoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _RoleService_GetList_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _RoleService_Save_Handler,
		},
		{
			MethodName: "UpStatus",
			Handler:    _RoleService_UpStatus_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _RoleService_Del_Handler,
		},
		{
			MethodName: "GetParent",
			Handler:    _RoleService_GetParent_Handler,
		},
		{
			MethodName: "GetMenuList",
			Handler:    _RoleService_GetMenuList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}

const (
	AccountService_GetList_FullMethodName        = "/system.AccountService/GetList"
	AccountService_Save_FullMethodName           = "/system.AccountService/Save"
	AccountService_UpState_FullMethodName        = "/system.AccountService/UpState"
	AccountService_Del_FullMethodName            = "/system.AccountService/Del"
	AccountService_GetRole_FullMethodName        = "/system.AccountService/GetRole"
	AccountService_Isaccountexist_FullMethodName = "/system.AccountService/Isaccountexist"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type AccountServiceClient interface {
	GetList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error)
	Save(ctx context.Context, in *SaveAccountRequest, opts ...grpc.CallOption) (*SaveAccountResponse, error)
	UpState(ctx context.Context, in *UpStatusAccountRequest, opts ...grpc.CallOption) (*UpStatusAccountResponse, error)
	Del(ctx context.Context, in *DelAccountRequest, opts ...grpc.CallOption) (*DelAccountResponse, error)
	GetRole(ctx context.Context, in *GetAccountRoleRequest, opts ...grpc.CallOption) (*GetAccountRoleResponse, error)
	Isaccountexist(ctx context.Context, in *IsAccountExistRequest, opts ...grpc.CallOption) (*IsAccountExistResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetList(ctx context.Context, in *GetRoleListRequest, opts ...grpc.CallOption) (*GetRoleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleListResponse)
	err := c.cc.Invoke(ctx, AccountService_GetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Save(ctx context.Context, in *SaveAccountRequest, opts ...grpc.CallOption) (*SaveAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpState(ctx context.Context, in *UpStatusAccountRequest, opts ...grpc.CallOption) (*UpStatusAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpStatusAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_UpState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Del(ctx context.Context, in *DelAccountRequest, opts ...grpc.CallOption) (*DelAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelAccountResponse)
	err := c.cc.Invoke(ctx, AccountService_Del_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetRole(ctx context.Context, in *GetAccountRoleRequest, opts ...grpc.CallOption) (*GetAccountRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountRoleResponse)
	err := c.cc.Invoke(ctx, AccountService_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Isaccountexist(ctx context.Context, in *IsAccountExistRequest, opts ...grpc.CallOption) (*IsAccountExistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAccountExistResponse)
	err := c.cc.Invoke(ctx, AccountService_Isaccountexist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// 定义服务
type AccountServiceServer interface {
	GetList(context.Context, *GetRoleListRequest) (*GetRoleListResponse, error)
	Save(context.Context, *SaveAccountRequest) (*SaveAccountResponse, error)
	UpState(context.Context, *UpStatusAccountRequest) (*UpStatusAccountResponse, error)
	Del(context.Context, *DelAccountRequest) (*DelAccountResponse, error)
	GetRole(context.Context, *GetAccountRoleRequest) (*GetAccountRoleResponse, error)
	Isaccountexist(context.Context, *IsAccountExistRequest) (*IsAccountExistResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) GetList(context.Context, *GetRoleListRequest) (*GetRoleListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAccountServiceServer) Save(context.Context, *SaveAccountRequest) (*SaveAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedAccountServiceServer) UpState(context.Context, *UpStatusAccountRequest) (*UpStatusAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpState not implemented")
}
func (UnimplementedAccountServiceServer) Del(context.Context, *DelAccountRequest) (*DelAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedAccountServiceServer) GetRole(context.Context, *GetAccountRoleRequest) (*GetAccountRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedAccountServiceServer) Isaccountexist(context.Context, *IsAccountExistRequest) (*IsAccountExistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Isaccountexist not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetList(ctx, req.(*GetRoleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Save(ctx, req.(*SaveAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpStatusAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpState(ctx, req.(*UpStatusAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Del_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Del(ctx, req.(*DelAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetRole(ctx, req.(*GetAccountRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Isaccountexist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAccountExistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Isaccountexist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Isaccountexist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Isaccountexist(ctx, req.(*IsAccountExistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _AccountService_GetList_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _AccountService_Save_Handler,
		},
		{
			MethodName: "UpState",
			Handler:    _AccountService_UpState_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _AccountService_Del_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _AccountService_GetRole_Handler,
		},
		{
			MethodName: "Isaccountexist",
			Handler:    _AccountService_Isaccountexist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}

const (
	LogService_GetLogin_FullMethodName           = "/system.LogService/GetLogin"
	LogService_DelLastLogin_FullMethodName       = "/system.LogService/DelLastLogin"
	LogService_GetOperation_FullMethodName       = "/system.LogService/GetOperation"
	LogService_DelLastOperation_FullMethodName   = "/system.LogService/DelLastOperation"
	LogService_GetOperationDetail_FullMethodName = "/system.LogService/GetOperationDetail"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type LogServiceClient interface {
	GetLogin(ctx context.Context, in *GetLogListRequest, opts ...grpc.CallOption) (*GetLogListResponse, error)
	DelLastLogin(ctx context.Context, in *DelLastLoginRequest, opts ...grpc.CallOption) (*DelLastLoginResponse, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error)
	DelLastOperation(ctx context.Context, in *DelLastOperationRequest, opts ...grpc.CallOption) (*DelLastOperationResponse, error)
	GetOperationDetail(ctx context.Context, in *GetOperationDetailRequest, opts ...grpc.CallOption) (*GetOperationDetailResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) GetLogin(ctx context.Context, in *GetLogListRequest, opts ...grpc.CallOption) (*GetLogListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogListResponse)
	err := c.cc.Invoke(ctx, LogService_GetLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) DelLastLogin(ctx context.Context, in *DelLastLoginRequest, opts ...grpc.CallOption) (*DelLastLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelLastLoginResponse)
	err := c.cc.Invoke(ctx, LogService_DelLastLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperationResponse)
	err := c.cc.Invoke(ctx, LogService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) DelLastOperation(ctx context.Context, in *DelLastOperationRequest, opts ...grpc.CallOption) (*DelLastOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelLastOperationResponse)
	err := c.cc.Invoke(ctx, LogService_DelLastOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetOperationDetail(ctx context.Context, in *GetOperationDetailRequest, opts ...grpc.CallOption) (*GetOperationDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperationDetailResponse)
	err := c.cc.Invoke(ctx, LogService_GetOperationDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
//
// 定义服务
type LogServiceServer interface {
	GetLogin(context.Context, *GetLogListRequest) (*GetLogListResponse, error)
	DelLastLogin(context.Context, *DelLastLoginRequest) (*DelLastLoginResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error)
	DelLastOperation(context.Context, *DelLastOperationRequest) (*DelLastOperationResponse, error)
	GetOperationDetail(context.Context, *GetOperationDetailRequest) (*GetOperationDetailResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) GetLogin(context.Context, *GetLogListRequest) (*GetLogListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogin not implemented")
}
func (UnimplementedLogServiceServer) DelLastLogin(context.Context, *DelLastLoginRequest) (*DelLastLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelLastLogin not implemented")
}
func (UnimplementedLogServiceServer) GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedLogServiceServer) DelLastOperation(context.Context, *DelLastOperationRequest) (*DelLastOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelLastOperation not implemented")
}
func (UnimplementedLogServiceServer) GetOperationDetail(context.Context, *GetOperationDetailRequest) (*GetOperationDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperationDetail not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call panics, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_GetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogin(ctx, req.(*GetLogListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_DelLastLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelLastLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).DelLastLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_DelLastLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).DelLastLogin(ctx, req.(*DelLastLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_DelLastOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelLastOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).DelLastOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_DelLastOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).DelLastOperation(ctx, req.(*DelLastOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetOperationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetOperationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetOperationDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetOperationDetail(ctx, req.(*GetOperationDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLogin",
			Handler:    _LogService_GetLogin_Handler,
		},
		{
			MethodName: "DelLastLogin",
			Handler:    _LogService_DelLastLogin_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _LogService_GetOperation_Handler,
		},
		{
			MethodName: "DelLastOperation",
			Handler:    _LogService_DelLastOperation_Handler,
		},
		{
			MethodName: "GetOperationDetail",
			Handler:    _LogService_GetOperationDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
