// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"system/internal/logic/deptservice"
	"system/internal/svc"
	"system/system"
)

type DeptServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedDeptServiceServer
}

func NewDeptServiceServer(svcCtx *svc.ServiceContext) *DeptServiceServer {
	return &DeptServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeptServiceServer) GetList(ctx context.Context, in *system.GetDeptListRequest) (*system.GetDeptListResponse, error) {
	l := deptservicelogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *DeptServiceServer) Save(ctx context.Context, in *system.SaveDeptRequest) (*system.SaveDeptResponse, error) {
	l := deptservicelogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

func (s *DeptServiceServer) UpState(ctx context.Context, in *system.UpStatusDeptRequest) (*system.UpStatusDeptResponse, error) {
	l := deptservicelogic.NewUpStateLogic(ctx, s.svcCtx)
	return l.UpState(in)
}

func (s *DeptServiceServer) Del(ctx context.Context, in *system.DelDeptRequest) (*system.DelDeptResponse, error) {
	l := deptservicelogic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *DeptServiceServer) GetParent(ctx context.Context, in *system.GetDeptParentRequest) (*system.GetDeptParentResponse, error) {
	l := deptservicelogic.NewGetParentLogic(ctx, s.svcCtx)
	return l.GetParent(in)
}
