// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.11
// source: apilog.proto

package apilog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`       // 账号ID
	BusinessId    int64                  `protobuf:"varint,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`    // 业务ID
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                   // 日志类型 admin后台日志 app端日志
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`                               // 请求方法 GET POST PUT DELETE
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`                                   // 请求路径
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`                                       // 请求IP
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`                             // IP地址
	ReqHeaders    string                 `protobuf:"bytes,9,opt,name=req_headers,json=reqHeaders,proto3" json:"req_headers,omitempty"`     // 请求头
	ReqBody       string                 `protobuf:"bytes,10,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`             // 请求体
	RespHeaders   string                 `protobuf:"bytes,11,opt,name=resp_headers,json=respHeaders,proto3" json:"resp_headers,omitempty"` // 响应头
	RespBody      string                 `protobuf:"bytes,12,opt,name=resp_body,json=respBody,proto3" json:"resp_body,omitempty"`          // 响应体
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`                             // 状态 1成功 0失败
	Duration      int64                  `protobuf:"varint,14,opt,name=duration,proto3" json:"duration,omitempty"`                         // 耗时(毫秒)
	CreateTime    string                 `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`    // 创建时间戳
	Description   string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`                    // 操作描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogRequest) Reset() {
	*x = OperationLogRequest{}
	mi := &file_apilog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogRequest) ProtoMessage() {}

func (x *OperationLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apilog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogRequest.ProtoReflect.Descriptor instead.
func (*OperationLogRequest) Descriptor() ([]byte, []int) {
	return file_apilog_proto_rawDescGZIP(), []int{0}
}

func (x *OperationLogRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OperationLogRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *OperationLogRequest) GetBusinessId() int64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *OperationLogRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OperationLogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperationLogRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OperationLogRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OperationLogRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OperationLogRequest) GetReqHeaders() string {
	if x != nil {
		return x.ReqHeaders
	}
	return ""
}

func (x *OperationLogRequest) GetReqBody() string {
	if x != nil {
		return x.ReqBody
	}
	return ""
}

func (x *OperationLogRequest) GetRespHeaders() string {
	if x != nil {
		return x.RespHeaders
	}
	return ""
}

func (x *OperationLogRequest) GetRespBody() string {
	if x != nil {
		return x.RespBody
	}
	return ""
}

func (x *OperationLogRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OperationLogRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *OperationLogRequest) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *OperationLogRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type OperationLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogResponse) Reset() {
	*x = OperationLogResponse{}
	mi := &file_apilog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogResponse) ProtoMessage() {}

func (x *OperationLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apilog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogResponse.ProtoReflect.Descriptor instead.
func (*OperationLogResponse) Descriptor() ([]byte, []int) {
	return file_apilog_proto_rawDescGZIP(), []int{1}
}

var File_apilog_proto protoreflect.FileDescriptor

const file_apilog_proto_rawDesc = "" +
	"\n" +
	"\fapilog.proto\x12\x06apilog\"\xcb\x03\n" +
	"\x13OperationLogRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\x03R\n" +
	"businessId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1f\n" +
	"\vreq_headers\x18\t \x01(\tR\n" +
	"reqHeaders\x12\x19\n" +
	"\breq_body\x18\n" +
	" \x01(\tR\areqBody\x12!\n" +
	"\fresp_headers\x18\v \x01(\tR\vrespHeaders\x12\x1b\n" +
	"\tresp_body\x18\f \x01(\tR\brespBody\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1a\n" +
	"\bduration\x18\x0e \x01(\x03R\bduration\x12\x1f\n" +
	"\vcreate_time\x18\x0f \x01(\tR\n" +
	"createTime\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\"\x16\n" +
	"\x14OperationLogResponse2Z\n" +
	"\n" +
	"LogService\x12L\n" +
	"\x0fAddOperationLog\x12\x1b.apilog.OperationLogRequest\x1a\x1c.apilog.OperationLogResponseB\n" +
	"Z\b./apilogb\x06proto3"

var (
	file_apilog_proto_rawDescOnce sync.Once
	file_apilog_proto_rawDescData []byte
)

func file_apilog_proto_rawDescGZIP() []byte {
	file_apilog_proto_rawDescOnce.Do(func() {
		file_apilog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apilog_proto_rawDesc), len(file_apilog_proto_rawDesc)))
	})
	return file_apilog_proto_rawDescData
}

var file_apilog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apilog_proto_goTypes = []any{
	(*OperationLogRequest)(nil),  // 0: apilog.OperationLogRequest
	(*OperationLogResponse)(nil), // 1: apilog.OperationLogResponse
}
var file_apilog_proto_depIdxs = []int32{
	0, // 0: apilog.LogService.AddOperationLog:input_type -> apilog.OperationLogRequest
	1, // 1: apilog.LogService.AddOperationLog:output_type -> apilog.OperationLogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apilog_proto_init() }
func file_apilog_proto_init() {
	if File_apilog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apilog_proto_rawDesc), len(file_apilog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apilog_proto_goTypes,
		DependencyIndexes: file_apilog_proto_depIdxs,
		MessageInfos:      file_apilog_proto_msgTypes,
	}.Build()
	File_apilog_proto = out.File
	file_apilog_proto_goTypes = nil
	file_apilog_proto_depIdxs = nil
}
