// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package server

import (
	"context"

	"system/internal/logic/logservice"
	"system/internal/svc"
	"system/system"
)

type LogServiceServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedLogServiceServer
}

func NewLogServiceServer(svcCtx *svc.ServiceContext) *LogServiceServer {
	return &LogServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *LogServiceServer) GetLogin(ctx context.Context, in *system.GetLogListRequest) (*system.GetLogListResponse, error) {
	l := logservicelogic.NewGetLoginLogic(ctx, s.svcCtx)
	return l.GetLogin(in)
}

func (s *LogServiceServer) DelLastLogin(ctx context.Context, in *system.DelLastLoginRequest) (*system.DelLastLoginResponse, error) {
	l := logservicelogic.NewDelLastLoginLogic(ctx, s.svcCtx)
	return l.DelLastLogin(in)
}

func (s *LogServiceServer) GetOperation(ctx context.Context, in *system.GetOperationRequest) (*system.GetOperationResponse, error) {
	l := logservicelogic.NewGetOperationLogic(ctx, s.svcCtx)
	return l.GetOperation(in)
}

func (s *LogServiceServer) DelLastOperation(ctx context.Context, in *system.DelLastOperationRequest) (*system.DelLastOperationResponse, error) {
	l := logservicelogic.NewDelLastOperationLogic(ctx, s.svcCtx)
	return l.DelLastOperation(in)
}

func (s *LogServiceServer) GetOperationDetail(ctx context.Context, in *system.GetOperationDetailRequest) (*system.GetOperationDetailResponse, error) {
	l := logservicelogic.NewGetOperationDetailLogic(ctx, s.svcCtx)
	return l.GetOperationDetail(in)
}
