// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package ruleservice

import (
	"context"

	"system/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelAccountRequest          = system.DelAccountRequest
	DelAccountResponse         = system.DelAccountResponse
	DelDeptRequest             = system.DelDeptRequest
	DelDeptResponse            = system.DelDeptResponse
	DelLastLoginRequest        = system.DelLastLoginRequest
	DelLastLoginResponse       = system.DelLastLoginResponse
	DelLastOperationRequest    = system.DelLastOperationRequest
	DelLastOperationResponse   = system.DelLastOperationResponse
	DelRoleRequest             = system.DelRoleRequest
	DelRoleResponse            = system.DelRoleResponse
	DelRuleRequest             = system.DelRuleRequest
	DelRuleResponse            = system.DelRuleResponse
	DeptData                   = system.DeptData
	DeptParentData             = system.DeptParentData
	GetAccountListRequest      = system.GetAccountListRequest
	GetAccountListResponse     = system.GetAccountListResponse
	GetAccountRoleRequest      = system.GetAccountRoleRequest
	GetAccountRoleResponse     = system.GetAccountRoleResponse
	GetDeptListRequest         = system.GetDeptListRequest
	GetDeptListResponse        = system.GetDeptListResponse
	GetDeptParentRequest       = system.GetDeptParentRequest
	GetDeptParentResponse      = system.GetDeptParentResponse
	GetLogListRequest          = system.GetLogListRequest
	GetLogListResponse         = system.GetLogListResponse
	GetMenuListRequest         = system.GetMenuListRequest
	GetMenuListResponse        = system.GetMenuListResponse
	GetOperationDetailRequest  = system.GetOperationDetailRequest
	GetOperationDetailResponse = system.GetOperationDetailResponse
	GetOperationRequest        = system.GetOperationRequest
	GetOperationResponse       = system.GetOperationResponse
	GetRoleListRequest         = system.GetRoleListRequest
	GetRoleListResponse        = system.GetRoleListResponse
	GetRoleParentRequest       = system.GetRoleParentRequest
	GetRoleParentResponse      = system.GetRoleParentResponse
	GetRoutesRequest           = system.GetRoutesRequest
	GetRoutesResponse          = system.GetRoutesResponse
	GetRuleContentRequest      = system.GetRuleContentRequest
	GetRuleContentResponse     = system.GetRuleContentResponse
	GetRuleListRequest         = system.GetRuleListRequest
	GetRuleListResponse        = system.GetRuleListResponse
	GetRuleParentRequest       = system.GetRuleParentRequest
	GetRuleParentResponse      = system.GetRuleParentResponse
	IsAccountExistRequest      = system.IsAccountExistRequest
	IsAccountExistResponse     = system.IsAccountExistResponse
	RoleData                   = system.RoleData
	SaveAccountRequest         = system.SaveAccountRequest
	SaveAccountResponse        = system.SaveAccountResponse
	SaveDeptRequest            = system.SaveDeptRequest
	SaveDeptResponse           = system.SaveDeptResponse
	SaveRoleRequest            = system.SaveRoleRequest
	SaveRoleResponse           = system.SaveRoleResponse
	SaveRuleRequest            = system.SaveRuleRequest
	SaveRuleResponse           = system.SaveRuleResponse
	UpStatusAccountRequest     = system.UpStatusAccountRequest
	UpStatusAccountResponse    = system.UpStatusAccountResponse
	UpStatusDeptRequest        = system.UpStatusDeptRequest
	UpStatusDeptResponse       = system.UpStatusDeptResponse
	UpStatusRoleRequest        = system.UpStatusRoleRequest
	UpStatusRoleResponse       = system.UpStatusRoleResponse
	UpStatusRuleRequest        = system.UpStatusRuleRequest
	UpStatusRuleResponse       = system.UpStatusRuleResponse

	RuleService interface {
		GetList(ctx context.Context, in *GetRuleListRequest, opts ...grpc.CallOption) (*GetRuleListResponse, error)
		Save(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error)
		UpStatus(ctx context.Context, in *UpStatusRuleRequest, opts ...grpc.CallOption) (*UpStatusRuleResponse, error)
		Del(ctx context.Context, in *DelRuleRequest, opts ...grpc.CallOption) (*DelRuleResponse, error)
		GetContent(ctx context.Context, in *GetRuleContentRequest, opts ...grpc.CallOption) (*GetRuleContentResponse, error)
		GetParent(ctx context.Context, in *GetRuleParentRequest, opts ...grpc.CallOption) (*GetRuleParentResponse, error)
		GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	}

	defaultRuleService struct {
		cli zrpc.Client
	}
)

func NewRuleService(cli zrpc.Client) RuleService {
	return &defaultRuleService{
		cli: cli,
	}
}

func (m *defaultRuleService) GetList(ctx context.Context, in *GetRuleListRequest, opts ...grpc.CallOption) (*GetRuleListResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultRuleService) Save(ctx context.Context, in *SaveRuleRequest, opts ...grpc.CallOption) (*SaveRuleResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.Save(ctx, in, opts...)
}

func (m *defaultRuleService) UpStatus(ctx context.Context, in *UpStatusRuleRequest, opts ...grpc.CallOption) (*UpStatusRuleResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.UpStatus(ctx, in, opts...)
}

func (m *defaultRuleService) Del(ctx context.Context, in *DelRuleRequest, opts ...grpc.CallOption) (*DelRuleResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.Del(ctx, in, opts...)
}

func (m *defaultRuleService) GetContent(ctx context.Context, in *GetRuleContentRequest, opts ...grpc.CallOption) (*GetRuleContentResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.GetContent(ctx, in, opts...)
}

func (m *defaultRuleService) GetParent(ctx context.Context, in *GetRuleParentRequest, opts ...grpc.CallOption) (*GetRuleParentResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.GetParent(ctx, in, opts...)
}

func (m *defaultRuleService) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	client := system.NewRuleServiceClient(m.cli.Conn())
	return client.GetRoutes(ctx, in, opts...)
}
