// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system.proto

package logservice

import (
	"context"

	"system/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelAccountRequest          = system.DelAccountRequest
	DelAccountResponse         = system.DelAccountResponse
	DelDeptRequest             = system.DelDeptRequest
	DelDeptResponse            = system.DelDeptResponse
	DelLastLoginRequest        = system.DelLastLoginRequest
	DelLastLoginResponse       = system.DelLastLoginResponse
	DelLastOperationRequest    = system.DelLastOperationRequest
	DelLastOperationResponse   = system.DelLastOperationResponse
	DelRoleRequest             = system.DelRoleRequest
	DelRoleResponse            = system.DelRoleResponse
	DelRuleRequest             = system.DelRuleRequest
	DelRuleResponse            = system.DelRuleResponse
	DeptData                   = system.DeptData
	DeptParentData             = system.DeptParentData
	GetAccountListRequest      = system.GetAccountListRequest
	GetAccountListResponse     = system.GetAccountListResponse
	GetAccountRoleRequest      = system.GetAccountRoleRequest
	GetAccountRoleResponse     = system.GetAccountRoleResponse
	GetDeptListRequest         = system.GetDeptListRequest
	GetDeptListResponse        = system.GetDeptListResponse
	GetDeptParentRequest       = system.GetDeptParentRequest
	GetDeptParentResponse      = system.GetDeptParentResponse
	GetLogListRequest          = system.GetLogListRequest
	GetLogListResponse         = system.GetLogListResponse
	GetMenuListRequest         = system.GetMenuListRequest
	GetMenuListResponse        = system.GetMenuListResponse
	GetOperationDetailRequest  = system.GetOperationDetailRequest
	GetOperationDetailResponse = system.GetOperationDetailResponse
	GetOperationRequest        = system.GetOperationRequest
	GetOperationResponse       = system.GetOperationResponse
	GetRoleListRequest         = system.GetRoleListRequest
	GetRoleListResponse        = system.GetRoleListResponse
	GetRoleParentRequest       = system.GetRoleParentRequest
	GetRoleParentResponse      = system.GetRoleParentResponse
	GetRoutesRequest           = system.GetRoutesRequest
	GetRoutesResponse          = system.GetRoutesResponse
	GetRuleContentRequest      = system.GetRuleContentRequest
	GetRuleContentResponse     = system.GetRuleContentResponse
	GetRuleListRequest         = system.GetRuleListRequest
	GetRuleListResponse        = system.GetRuleListResponse
	GetRuleParentRequest       = system.GetRuleParentRequest
	GetRuleParentResponse      = system.GetRuleParentResponse
	IsAccountExistRequest      = system.IsAccountExistRequest
	IsAccountExistResponse     = system.IsAccountExistResponse
	RoleData                   = system.RoleData
	SaveAccountRequest         = system.SaveAccountRequest
	SaveAccountResponse        = system.SaveAccountResponse
	SaveDeptRequest            = system.SaveDeptRequest
	SaveDeptResponse           = system.SaveDeptResponse
	SaveRoleRequest            = system.SaveRoleRequest
	SaveRoleResponse           = system.SaveRoleResponse
	SaveRuleRequest            = system.SaveRuleRequest
	SaveRuleResponse           = system.SaveRuleResponse
	UpStatusAccountRequest     = system.UpStatusAccountRequest
	UpStatusAccountResponse    = system.UpStatusAccountResponse
	UpStatusDeptRequest        = system.UpStatusDeptRequest
	UpStatusDeptResponse       = system.UpStatusDeptResponse
	UpStatusRoleRequest        = system.UpStatusRoleRequest
	UpStatusRoleResponse       = system.UpStatusRoleResponse
	UpStatusRuleRequest        = system.UpStatusRuleRequest
	UpStatusRuleResponse       = system.UpStatusRuleResponse

	LogService interface {
		GetLogin(ctx context.Context, in *GetLogListRequest, opts ...grpc.CallOption) (*GetLogListResponse, error)
		DelLastLogin(ctx context.Context, in *DelLastLoginRequest, opts ...grpc.CallOption) (*DelLastLoginResponse, error)
		GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error)
		DelLastOperation(ctx context.Context, in *DelLastOperationRequest, opts ...grpc.CallOption) (*DelLastOperationResponse, error)
		GetOperationDetail(ctx context.Context, in *GetOperationDetailRequest, opts ...grpc.CallOption) (*GetOperationDetailResponse, error)
	}

	defaultLogService struct {
		cli zrpc.Client
	}
)

func NewLogService(cli zrpc.Client) LogService {
	return &defaultLogService{
		cli: cli,
	}
}

func (m *defaultLogService) GetLogin(ctx context.Context, in *GetLogListRequest, opts ...grpc.CallOption) (*GetLogListResponse, error) {
	client := system.NewLogServiceClient(m.cli.Conn())
	return client.GetLogin(ctx, in, opts...)
}

func (m *defaultLogService) DelLastLogin(ctx context.Context, in *DelLastLoginRequest, opts ...grpc.CallOption) (*DelLastLoginResponse, error) {
	client := system.NewLogServiceClient(m.cli.Conn())
	return client.DelLastLogin(ctx, in, opts...)
}

func (m *defaultLogService) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error) {
	client := system.NewLogServiceClient(m.cli.Conn())
	return client.GetOperation(ctx, in, opts...)
}

func (m *defaultLogService) DelLastOperation(ctx context.Context, in *DelLastOperationRequest, opts ...grpc.CallOption) (*DelLastOperationResponse, error) {
	client := system.NewLogServiceClient(m.cli.Conn())
	return client.DelLastOperation(ctx, in, opts...)
}

func (m *defaultLogService) GetOperationDetail(ctx context.Context, in *GetOperationDetailRequest, opts ...grpc.CallOption) (*GetOperationDetailResponse, error) {
	client := system.NewLogServiceClient(m.cli.Conn())
	return client.GetOperationDetail(ctx, in, opts...)
}
